import type { AssessmentAnswers } from '@/app/report/_engine/types'

// Seven personas — one per non-construction industry — to demo the matrix end-to-end.

export const dentalAnswers: AssessmentAnswers = {
  reportId: 'sample-dental-practice',
  ownerName: 'Dr. Sarah Chen',
  ownerFirstName: 'Sarah',
  company: 'Harborview Dental',
  trade: 'General + cosmetic dentistry practice',
  industry: 'appointment-based',
  customerType: 'consumer',
  revenueModel: 'per-visit',
  yearsInBusiness: 12,
  teamSize: 7,
  location: 'Victoria, BC',
  topPain: 'front desk constantly overwhelmed',
  leadSources: ['google', 'referrals', 'repeat', 'directory'],
  primaryIntake: 'office',
  afterHoursHandling: 'voicemail',
  leadsLostAfterHoursPerMonth: 3,
  leadResponseTime: 'same-day',
  leadsPerMonth: 22,
  closeRate: 0.55,
  avgTicket: 420,
  bookingTool: 'other-ehr',
  noShowRatePerWeek: 3,
  recurringClientPct: 0.72,
  visitsPerWeek: 80,
  avgVisitValue: 220,
  accountingTool: 'quickbooks',
  invoiceDelayDays: 1,
  chasingPayments: true,
  chasingPaymentsAmount: 12000,
  hasWebsite: true,
  websiteAgeYears: 4,
  googleReviewCount: 52,
  asksForReviews: false,
  runsAds: [],
  wantedTimeBack: ['front-desk-phone', 'recall-outreach'],
  keepsUpAtNight: ['no-shows', 'insurance-chasing'],
  leavingMoneyOnTable: ['no-recall-campaign', 'no-online-booking', 'passive-reviews'],
  softwareThatFlopped: ['generic-crm'],
  officeSize: 3,
}

export const lawFirmAnswers: AssessmentAnswers = {
  reportId: 'sample-law-firm',
  ownerName: 'Marcus Ellis',
  ownerFirstName: 'Marcus',
  company: 'Ellis Legal',
  trade: 'Small business + estate planning law practice',
  industry: 'professional-services',
  customerType: 'both',
  revenueModel: 'hourly',
  yearsInBusiness: 5,
  teamSize: 2,
  location: 'Calgary, AB',
  topPain: 'client intake paperwork + engagement letters',
  leadSources: ['referrals', 'directory'],
  primaryIntake: 'owner',
  afterHoursHandling: 'voicemail',
  leadsLostAfterHoursPerMonth: 2,
  leadResponseTime: 'next-day',
  leadsPerMonth: 12,
  closeRate: 0.5,
  avgTicket: 3200,
  billingModel: 'hybrid',
  timeTrackingTool: 'clio',
  arAging60PlusPct: 0.28,
  newClientFlow: 'referral-only',
  accountingTool: 'quickbooks',
  invoiceDelayDays: 14,
  chasingPayments: true,
  chasingPaymentsAmount: 24000,
  hasWebsite: true,
  websiteAgeYears: 3,
  googleReviewCount: 6,
  asksForReviews: false,
  runsAds: [],
  wantedTimeBack: ['intake-paperwork', 'invoicing', 'chasing-AR'],
  keepsUpAtNight: ['AR-backlog', 'referral-dependency'],
  leavingMoneyOnTable: ['no-content', 'slow-intake', 'no-online-reviews'],
  softwareThatFlopped: [],
  officeSize: 1,
}

export const shopifyAnswers: AssessmentAnswers = {
  reportId: 'sample-shopify-brand',
  ownerName: 'Priya Nakamura',
  ownerFirstName: 'Priya',
  company: 'LumenShop',
  trade: 'DTC skincare brand',
  industry: 'ecommerce',
  customerType: 'consumer',
  revenueModel: 'transactional',
  yearsInBusiness: 4,
  teamSize: 3,
  location: 'Toronto, ON',
  topPain: 'ad costs eating margin + high return rate',
  ecomPlatform: 'shopify',
  monthlyRevenueBand: '50k-250k',
  aov: 85,
  returnRate: 0.12,
  adSpendPct: 0.35,
  fulfillment: '3pl',
  leadSources: ['google', 'social-organic'],
  avgTicket: 85,
  leadsPerMonth: 2400,
  closeRate: 0.025,
  accountingTool: 'quickbooks',
  invoiceDelayDays: 0,
  chasingPayments: false,
  hasWebsite: true,
  websiteAgeYears: 2,
  googleReviewCount: 0,
  asksForReviews: true,
  runsAds: ['meta', 'google', 'tiktok'],
  wantedTimeBack: ['customer-support', 'abandoned-cart-manual'],
  keepsUpAtNight: ['margin-erosion', 'ad-account-dependency'],
  leavingMoneyOnTable: ['no-klaviyo-flows', 'no-post-purchase', 'slow-site'],
  softwareThatFlopped: ['generic-crm', 'generic-ad-tool'],
}

export const cafeAnswers: AssessmentAnswers = {
  reportId: 'sample-coffee-shop',
  ownerName: 'Maya Okonkwo',
  ownerFirstName: 'Maya',
  company: 'Threadline Coffee',
  trade: 'Specialty coffee shop + light lunch',
  industry: 'retail',
  customerType: 'consumer',
  revenueModel: 'transactional',
  yearsInBusiness: 3,
  teamSize: 6,
  location: 'Toronto, ON',
  topPain: 'peak-hour line management + thin margins',
  posSystem: 'square',
  walkInPct: 0.9,
  onlineOrdering: false,
  loyaltyProgram: false,
  transactionsPerDay: 200,
  peakHours: '7–9am, 12–1pm',
  leadSources: ['walk-in', 'google', 'repeat', 'social-organic'],
  avgTicket: 11,
  leadsPerMonth: 4500,
  closeRate: 1,
  accountingTool: 'quickbooks',
  invoiceDelayDays: 0,
  chasingPayments: false,
  hasWebsite: true,
  websiteAgeYears: 3,
  googleReviewCount: 15,
  asksForReviews: false,
  runsAds: ['instagram'],
  wantedTimeBack: ['admin', 'scheduling-staff'],
  keepsUpAtNight: ['peak-line-losing-customers', 'staff-turnover'],
  leavingMoneyOnTable: ['no-online-ordering', 'no-loyalty', 'passive-GBP'],
  softwareThatFlopped: [],
}

export const agencyAnswers: AssessmentAnswers = {
  reportId: 'sample-marketing-agency',
  ownerName: 'Zach Patel',
  ownerFirstName: 'Zach',
  company: 'Nova Creative',
  trade: 'Brand identity + web design agency',
  industry: 'project-based',
  customerType: 'business',
  revenueModel: 'per-project',
  yearsInBusiness: 5,
  teamSize: 4,
  location: 'Brooklyn, NY',
  topPain: 'quoting is a 4-day process every time',
  leadSources: ['referrals', 'social-organic', 'partner'],
  primaryIntake: 'owner',
  afterHoursHandling: 'office-hours-only',
  leadsLostAfterHoursPerMonth: 0,
  leadResponseTime: 'same-day',
  leadsPerMonth: 12,
  closeRate: 0.3,
  avgTicket: 28000,
  quotingTool: 'excel',
  quotingSpeedDays: 4,
  quoteFollowUp: 'sometimes',
  jobMgmtTool: 'none',
  changeOrderProcess: 'email',
  clientCommsStyle: 'reactive',
  accountingTool: 'quickbooks',
  invoiceDelayDays: 7,
  chasingPayments: true,
  chasingPaymentsAmount: 35000,
  hasWebsite: true,
  websiteAgeYears: 2,
  googleReviewCount: 9,
  asksForReviews: false,
  runsAds: [],
  wantedTimeBack: ['quoting', 'project-management', 'client-comms'],
  keepsUpAtNight: ['dry-months', 'scope-creep'],
  leavingMoneyOnTable: ['no-retainers', 'slow-quoting', 'no-case-studies'],
  softwareThatFlopped: ['asana-for-clients'],
  officeSize: 1,
}

export const saasAnswers: AssessmentAnswers = {
  reportId: 'sample-saas-startup',
  ownerName: 'Tam Nguyen',
  ownerFirstName: 'Tam',
  company: 'Relay',
  trade: 'B2B SaaS — ops automation for logistics SMBs',
  industry: 'b2b-saas',
  customerType: 'business',
  revenueModel: 'subscription',
  yearsInBusiness: 3,
  teamSize: 5,
  location: 'Austin, TX',
  topPain: 'pipeline discipline + 30-day churn too high',
  stage: 'under-50k-mrr',
  salesCycleDays: 45,
  crm: 'spreadsheet',
  demoCloseRate: 0.15,
  primaryChannel: 'outbound',
  churnRatePct: 0.08,
  leadSources: ['partner', 'social-organic'],
  primaryIntake: 'owner',
  afterHoursHandling: 'office-hours-only',
  leadResponseTime: 'same-day',
  leadsPerMonth: 40,
  closeRate: 0.15,
  avgTicket: 6000,
  accountingTool: 'xero',
  invoiceDelayDays: 0,
  chasingPayments: false,
  hasWebsite: true,
  websiteAgeYears: 1,
  googleReviewCount: 2,
  asksForReviews: false,
  runsAds: ['linkedin', 'google'],
  wantedTimeBack: ['manual-CRM-updates', 'outbound-list-building'],
  keepsUpAtNight: ['churn', 'pipeline-coverage', 'demo-no-shows'],
  leavingMoneyOnTable: ['no-onboarding', 'no-expansion-motion', 'leaky-funnel'],
  softwareThatFlopped: ['salesforce-too-heavy'],
  officeSize: 0,
}

export const photographerAnswers: AssessmentAnswers = {
  reportId: 'sample-photographer',
  ownerName: 'Hannah Torres',
  ownerFirstName: 'Hannah',
  company: 'Stillframe Studio',
  trade: 'Wedding + elopement photography',
  industry: 'creative',
  customerType: 'consumer',
  revenueModel: 'per-project',
  yearsInBusiness: 4,
  teamSize: 1,
  location: 'Halifax, NS',
  topPain: 'delivery takes 6–8 weeks, clients get antsy',
  pricingModel: 'package',
  bookingLeadDays: 180,
  portfolioPlatform: 'squarespace',
  assetDeliveryTool: 'dropbox',
  leadSources: ['google', 'referrals', 'social-organic'],
  primaryIntake: 'owner',
  afterHoursHandling: 'office-hours-only',
  leadResponseTime: 'same-day',
  leadsPerMonth: 18,
  closeRate: 0.35,
  avgTicket: 3800,
  quotingTool: 'other',
  quotingSpeedDays: 2,
  quoteFollowUp: 'sometimes',
  accountingTool: 'freshbooks',
  invoiceDelayDays: 5,
  chasingPayments: false,
  hasWebsite: true,
  websiteAgeYears: 2,
  googleReviewCount: 28,
  asksForReviews: true,
  runsAds: ['instagram'],
  wantedTimeBack: ['culling-photos', 'delivery-workflow', 'admin'],
  keepsUpAtNight: ['seasonality', 'delivery-stress'],
  leavingMoneyOnTable: ['no-print-sales', 'slow-delivery', 'no-referral-program'],
  softwareThatFlopped: [],
  officeSize: 0,
}
