// Extended recommendation library — recs for the 6 non-construction industries.
// The matcher combines this with LIBRARY from library.ts to get the full set.

import type { AssessmentAnswers, LibraryRec } from './types'
import { teamSize } from './types'

const missedVisitsDollars = (a: AssessmentAnswers) => {
  const avg = a.avgVisitValue ?? a.avgTicket ?? 0
  const misses = a.noShowRatePerWeek ?? 0
  return Math.round(misses * 4 * avg)
}

export const LIBRARY_EXTRAS: LibraryRec[] = [
  // APPOINTMENT-BASED
  {
    id: 't1-booking-link',
    tier: 1,
    category: 'booking',
    industries: ['appointment-based', 'trades', 'professional-services', 'creative'],
    title: 'Self-serve online booking link',
    pitch: 'Stop playing phone tag. Clients pick their own slot and it drops on your calendar.',
    effort: 'Easy',
    setupHours: '30 min',
    cost: 'Free (Calendly / Square / Acuity trials)',
    fixes: (a) =>
      a.bookingTool === 'phone-only'
        ? 'You only book by phone — industry data says 40% of patients/clients prefer booking online and will pick a competitor who lets them.'
        : 'Switching to a real booking tool cuts back-and-forth and surfaces your availability publicly.',
    roi: () => ({
      hoursPerWeek: 4,
      dollarsPerMonth: 3000,
      summary: '4 hrs/week back on phone tag + 20% more bookings from online convenience ≈ $3k/mo',
    }),
    diyGuide: {
      tools: ['Calendly, Square Appointments, or Acuity (pick one)'],
      steps: [
        'Sign up for Calendly free tier (or Square Appointments if you take payments)',
        'Create event types for each service you offer with duration + buffer',
        'Connect your Google / Outlook calendar so double-booking is impossible',
        'Add the link to your voicemail greeting, email signature, and homepage',
        'Test by booking yourself',
      ],
    },
    cta: null,
    triggers: (a) => a.bookingTool === 'phone-only' || a.bookingTool === 'spreadsheet' || !a.bookingTool,
    priority: (a) => 45 + (a.bookingTool === 'phone-only' ? 15 : 0),
  },
  {
    id: 't1-noshow-reminders',
    tier: 1,
    category: 'booking',
    industries: ['appointment-based', 'trades', 'creative'],
    title: 'Automated appointment reminders (SMS + email)',
    pitch: 'Two reminders cuts no-shows in half. Most booking tools have this free — just turn it on.',
    effort: 'Easy',
    setupHours: '20 min',
    cost: 'Free (inside most booking tools)',
    fixes: (a) =>
      a.noShowRatePerWeek && a.noShowRatePerWeek > 0
        ? `${a.noShowRatePerWeek} no-shows/week × $${a.avgVisitValue ?? a.avgTicket ?? 150} = $${Math.round((a.noShowRatePerWeek ?? 0) * 4 * (a.avgVisitValue ?? a.avgTicket ?? 150) / 1000)}k/mo in empty chair time.`
        : "Any no-show is revenue you staffed for but didn't collect. Automated reminders halve the rate.",
    roi: (a) => ({
      dollarsPerMonth: Math.max(1500, missedVisitsDollars(a) / 2),
      summary: `Cut no-shows ~50% ≈ $${Math.round(Math.max(1500, missedVisitsDollars(a) / 2) / 1000)}k/mo recovered`,
    }),
    diyGuide: {
      tools: ['Your existing booking tool'],
      steps: [
        'In your booking tool settings, find "Reminders" or "Notifications"',
        'Enable SMS reminder 24 hours before appointment',
        'Enable SMS reminder 2 hours before appointment',
        'Add a short no-show policy to your confirmation email ("late cancel: 50% charge")',
        "Review no-show rate monthly to confirm it's dropping",
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'appointment-based' || (a.noShowRatePerWeek ?? 0) > 0,
    priority: (a) => 40 + Math.min((a.noShowRatePerWeek ?? 0) * 5, 30),
  },
  {
    id: 't2-intake-forms',
    tier: 2,
    category: 'intake',
    industries: ['appointment-based', 'professional-services'],
    title: 'Digital intake + consent forms',
    pitch: 'Clients fill everything before they walk in. No more clipboard ritual, no more no-show dropouts.',
    effort: 'Medium',
    setupHours: '6–10 hrs',
    cost: '$1,200 setup + $30/mo',
    fixes: () =>
      'Paper intake costs you 15 min/client and drives no-shows (people avoid the friction). Digital intake kills both.',
    roi: () => ({
      hoursPerWeek: 4,
      dollarsPerMonth: 2200,
      summary: '4 hrs/week saved at the front desk + 15% no-show reduction ≈ $2.2k/mo',
    }),
    whatYouGet: [
      'JotForm or Typeform intake matched to your specialty',
      'Auto-send with booking confirmation',
      'Integration with your practice management system (if supported)',
      'Consent + HIPAA/PIPEDA compliance (where applicable)',
      'Custom branding on every form',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'appointment-based' || a.industry === 'professional-services',
    priority: () => 35,
  },
  {
    id: 't2-recall-campaign',
    tier: 2,
    category: 'marketing',
    industries: ['appointment-based', 'trades'],
    title: 'Recurring visit recall campaign',
    pitch: 'Automated "time for your next visit" texts 6 and 3 weeks ahead. Predictable rebooking.',
    effort: 'Medium',
    setupHours: '4–6 hrs',
    cost: '$900 setup + $49/mo',
    fixes: (a) =>
      a.recurringClientPct && a.recurringClientPct > 0.3
        ? `${Math.round((a.recurringClientPct ?? 0) * 100)}% of your clients rebook — recall automation lifts that to 60–70% without any extra work from you.`
        : 'Most appointment-based businesses under-book recurring clients because they rely on the client to remember.',
    roi: () => ({
      dollarsPerMonth: 4500,
      summary: 'Typical recall bumps rebook rate by 20pp ≈ $4.5k/mo recurring',
    }),
    whatYouGet: [
      "SMS + email campaign hitting 6 / 3 / 1 weeks before each client's next visit",
      'Integrated with your booking tool so sent-to status is tracked',
      'A/B tested message wording for your specialty',
      'Monthly recall-performance report',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'appointment-based' || (a.maintenancePct ?? 0) > 0,
    priority: (a) => 40 + ((a.recurringClientPct ?? 0) > 0.3 ? 15 : 0),
  },
  {
    id: 't3-ai-front-desk',
    tier: 3,
    category: 'intake',
    industries: ['appointment-based', 'trades', 'professional-services'],
    title: 'AI front desk — answers calls, books, reschedules',
    pitch: 'An AI receptionist that picks up every call, answers routine questions, books slots, and routes emergencies.',
    effort: 'Big',
    setupHours: '40–60 hrs',
    cost: '$6,500 build + $250/mo',
    priceAnchor: 'Typical part-time receptionist: $35k/yr · This AI: $3k/yr · Pays back in month 1',
    fixes: () =>
      "Every call your front desk handles during a busy hour is one they can't attend to the patient in front of them. The AI handles 60% of routine intake calls.",
    roi: () => ({
      hoursPerWeek: 12,
      dollarsPerMonth: 7000,
      summary: 'Free your front desk 12 hrs/week + never miss after-hours bookings ≈ $7k/mo',
    }),
    whatYouGet: [
      'Custom AI trained on your services, providers, insurance accepted',
      'Books + reschedules appointments directly into your PMS / booking tool',
      'Answers common questions (hours, parking, insurance, prep instructions)',
      'Escalates emergencies and complex calls to a human',
      'Texts call summaries to the office',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'appointment-based' || a.industry === 'professional-services',
    priority: (a) => 55 + (teamSize(a) >= 3 ? 10 : 0),
  },

  // RETAIL / WALK-IN / FOOD
  {
    id: 't1-gmb-retail',
    tier: 1,
    category: 'marketing',
    industries: ['retail', 'appointment-based', 'trades'],
    title: 'Google Business Profile for walk-in traffic',
    pitch: 'Your profile IS your signage on the internet. Most retailers leave half the fields empty.',
    effort: 'Easy',
    setupHours: '2 hrs',
    cost: 'Free',
    fixes: () => 'Google Maps is where 80% of foot traffic decisions happen. A complete profile shows up 5x more than an incomplete one.',
    roi: () => ({
      dollarsPerMonth: 3500,
      summary: 'Typical retail sees +30% calls/directions requests within 30 days ≈ $3.5k/mo',
    }),
    diyGuide: {
      tools: ['Google Business Profile'],
      steps: [
        'Fill every field: services, categories, hours, holiday hours, attributes',
        'Upload 25+ photos: exterior, interior, products, team, happy customers',
        'Enable Messaging and respond within 2 hours (or Google penalizes ranking)',
        'Post weekly: new arrivals, seasonal items, behind-the-scenes',
        'Add your menu / service list / product catalog if available',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'retail' || a.industry === 'appointment-based',
    priority: () => 40,
  },
  {
    id: 't2-loyalty-setup',
    tier: 2,
    category: 'marketing',
    industries: ['retail', 'appointment-based'],
    title: 'Square / Toast / Clover loyalty program setup',
    pitch: 'Customers who join loyalty spend 2–3x more per visit. Your POS can do this already.',
    effort: 'Medium',
    setupHours: '4–6 hrs',
    cost: '$900 setup',
    fixes: (a) =>
      !a.loyaltyProgram
        ? "You're leaving the easiest retention tool on the table. Most POSes include loyalty for $0."
        : 'A better configured loyalty program drives 20%+ more repeat visits.',
    roi: () => ({
      dollarsPerMonth: 3000,
      summary: 'Loyalty members spend 2.5x per visit ≈ $3k/mo uplift',
    }),
    whatYouGet: [
      'Points structure and reward tiers configured in your POS',
      'Customer email capture flow at checkout',
      'Welcome email + birthday email automation',
      'Monthly dashboard of new members and redemption rate',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'retail' && !a.loyaltyProgram,
    priority: (a) => 40 + (a.posSystem === 'square' || a.posSystem === 'toast' || a.posSystem === 'clover' ? 10 : 0),
  },
  {
    id: 't2-online-ordering',
    tier: 2,
    category: 'ecom',
    industries: ['retail'],
    title: 'Online ordering + pickup setup',
    pitch: "Capture the customer who wants your product but doesn't want to wait. Square / Toast make this 1-click.",
    effort: 'Medium',
    setupHours: '8–12 hrs',
    cost: '$1,500 setup + POS % per order',
    fixes: (a) =>
      !a.onlineOrdering
        ? "You're not capturing pickup orders — every time your store gets busy, you lose walk-ins who won't wait."
        : '',
    roi: () => ({
      dollarsPerMonth: 5000,
      summary: 'Pickup orders add 15–25% to monthly revenue ≈ $5k/mo',
    }),
    whatYouGet: [
      'Online ordering site connected to your POS',
      'Menu / product catalog with photos + modifiers',
      'Pickup time slots + capacity management',
      'Stripe / Square payment integration',
      'SMS notifications when order is ready',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'retail' && !a.onlineOrdering,
    priority: (a) => 35 + ((a.transactionsPerDay ?? 0) > 50 ? 10 : 0),
  },
  {
    id: 't3-retail-analytics-dashboard',
    tier: 3,
    category: 'ops',
    industries: ['retail'],
    title: 'Custom retail analytics dashboard',
    pitch: 'One dashboard: top items by margin, slowest-moving SKUs, busiest hours, repeat-customer rate. Built on your POS data.',
    effort: 'Big',
    setupHours: '40–60 hrs',
    cost: '$7,500 build + $150/mo',
    priceAnchor: 'Typical analyst / BI team cost: $80k+/yr · This dashboard: $1,800/yr',
    fixes: () => "Your POS has the data but the reports are terrible. A proper dashboard surfaces the decisions you're flying blind on.",
    roi: () => ({
      hoursPerWeek: 3,
      dollarsPerMonth: 4500,
      summary: 'Smarter inventory + hours decisions ≈ $4.5k/mo margin + 3 hrs/week back',
    }),
    whatYouGet: [
      'Custom web dashboard pulling from Square/Toast/Clover API',
      'Top items by margin (not just revenue)',
      'Slow-movers flagged for clearance',
      'Hour-by-hour sales heatmap',
      'Repeat customer vs. first-time ratio',
      'iPad mode for in-store viewing',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'retail' && teamSize(a) >= 3,
    priority: () => 30,
  },

  // E-COMMERCE
  {
    id: 't1-abandoned-cart',
    tier: 1,
    category: 'ecom',
    industries: ['ecommerce'],
    title: 'Abandoned cart email sequence',
    pitch: 'Recover 10–15% of abandoned carts with a 3-email sequence. Every platform includes this free.',
    effort: 'Easy',
    setupHours: '2 hrs',
    cost: 'Free (Shopify / Klaviyo free tier)',
    fixes: () => '60–80% of carts get abandoned. A basic 3-email recovery sequence claws back 10–15% of them.',
    roi: (a) => ({
      dollarsPerMonth: Math.round((a.aov ?? 75) * 40),
      summary: `Recover 30–50 abandoned carts/mo at $${a.aov ?? 75} AOV ≈ $${Math.round((a.aov ?? 75) * 40 / 1000)}k/mo`,
    }),
    diyGuide: {
      tools: ['Shopify Email, Klaviyo, or Mailchimp'],
      steps: [
        'Email 1 (1 hr after abandon): "You left something behind — checkout here"',
        'Email 2 (24 hr later): Product spotlight + reviews + subtle scarcity',
        'Email 3 (3 days later): 10% off code (only if you run promos)',
        'Turn on conversion tracking to see which email performs',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'ecommerce',
    priority: () => 55,
  },
  {
    id: 't1-google-shopping-feed',
    tier: 1,
    category: 'marketing',
    industries: ['ecommerce'],
    title: 'Google Merchant Center feed',
    pitch: "Free product listings on Google Shopping. Most Shopify stores haven't set this up.",
    effort: 'Easy',
    setupHours: '1.5 hrs',
    cost: 'Free',
    fixes: () => 'Organic Google Shopping listings are free and most stores skip them. 10x the product visibility.',
    roi: () => ({
      dollarsPerMonth: 2500,
      summary: 'Free Google Shopping traffic ≈ $2.5k/mo for typical SMB store',
    }),
    diyGuide: {
      tools: ['Google Merchant Center', 'Shopify Google Channel app'],
      steps: [
        'Create Google Merchant Center account using your domain',
        'Verify and claim the domain',
        'Install the Google Channel app on Shopify',
        'Sync your product feed — Shopify handles the schema automatically',
        'Wait 48 hours for approval; then products appear in free Google Shopping results',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'ecommerce',
    priority: () => 40,
  },
  {
    id: 't2-klaviyo-flows',
    tier: 2,
    category: 'marketing',
    industries: ['ecommerce'],
    title: 'Klaviyo email flows setup (6 core flows)',
    pitch: 'Welcome, abandoned cart, post-purchase, win-back, browse abandonment, birthday. These 6 flows drive 25–40% of e-com revenue.',
    effort: 'Medium',
    setupHours: '12–16 hrs',
    cost: '$1,800 setup + Klaviyo: $35+/mo',
    fixes: () => "Industry benchmark: email drives 25–40% of e-com revenue. If you're not there, this is where the money is.",
    roi: () => ({
      dollarsPerMonth: 6000,
      summary: 'Target: 25% of revenue from email. Typical $50k/mo store sees $12k/mo from flows (we target $6k minimum)',
    }),
    whatYouGet: [
      'Welcome flow (3 emails): brand story → best-sellers → coupon',
      'Abandoned cart (3 emails): 1hr, 24hr, 3 days',
      'Post-purchase (4 emails): confirmation → delivery → review request → cross-sell',
      'Win-back (3 emails for customers silent 60+ days)',
      'Browse abandonment (2 emails for product page views without add-to-cart)',
      'Birthday automation',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'ecommerce',
    priority: () => 50,
  },
  {
    id: 't2-shopify-speed',
    tier: 2,
    category: 'ecom',
    industries: ['ecommerce'],
    title: 'Shopify speed + conversion optimization',
    pitch: '1-second page load improvement = 7% more conversions. We audit and fix.',
    effort: 'Medium',
    setupHours: '8–12 hrs',
    cost: '$1,500',
    fixes: () => 'Most Shopify stores score 40–60 on PageSpeed. Getting to 80+ is a 10–15% conversion lift.',
    roi: () => ({
      dollarsPerMonth: 4000,
      summary: 'Speed + conversion fixes ≈ $4k/mo uplift on a typical store',
    }),
    whatYouGet: [
      'PageSpeed + Core Web Vitals audit with prioritized fixes',
      'Image optimization + lazy loading',
      'Unused app + script removal',
      'Theme liquid optimization',
      'Before/after speed scores in a deliverable report',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'ecommerce',
    priority: () => 40,
  },
  {
    id: 't3-ecom-ops-stack',
    tier: 3,
    category: 'ops',
    industries: ['ecommerce'],
    title: 'End-to-end e-commerce ops stack (3PL, returns, CX)',
    pitch: 'Shopify + Klaviyo + Gorgias + ShipStation + 3PL — integrated, configured, automated. Every ops lever tuned.',
    effort: 'Big',
    setupHours: '120–180 hrs',
    cost: '$18,000 build',
    priceAnchor: 'Typical COO hire: $120k/yr · This system: $18k one-time',
    fixes: () => 'Your tools are siloed — every tool working by itself is 10% of the value vs. integrated.',
    roi: () => ({
      hoursPerWeek: 15,
      dollarsPerMonth: 10000,
      summary: 'Saves ~15 hrs/week of manual ops + recovers 15% revenue via better CX/returns/email ≈ $10k/mo',
    }),
    whatYouGet: [
      'Klaviyo with 10+ flows configured',
      'Gorgias / Zendesk CX ticketing integrated with Shopify',
      'Returns automation (Loop or Returnly)',
      'ShipStation / 3PL integration',
      'Inventory sync across channels (Shopify + Amazon + Etsy)',
      'Custom executive dashboard',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'ecommerce' && (a.monthlyRevenueBand === '50k-250k' || a.monthlyRevenueBand === '250k-1m' || a.monthlyRevenueBand === '1m-plus'),
    priority: () => 35,
  },

  // PROFESSIONAL SERVICES
  {
    id: 't1-engagement-letter-template',
    tier: 1,
    category: 'quoting',
    industries: ['professional-services'],
    title: 'Engagement letter + retainer template (Google Docs)',
    pitch: "One polished template you fill in 30 seconds vs. Frankensteining from last week's email.",
    effort: 'Easy',
    setupHours: '1 hr',
    cost: 'Free',
    fixes: () => 'Most solo pros reinvent the engagement letter every time. A template cuts 30 min/client and looks more professional.',
    roi: () => ({
      hoursPerWeek: 3,
      summary: 'Save 3 hrs/week of copy-paste + look more polished at intake',
    }),
    diyGuide: {
      tools: ['Google Docs'],
      steps: [
        'Compile your best engagement letter from the past year',
        'Replace all client-specific details with [PLACEHOLDERS]',
        'Save as a Google Doc template',
        'Use "File > Make a copy" for each new client',
        'Bonus: use PandaDoc free tier to add e-signature',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'professional-services',
    priority: () => 30,
  },
  {
    id: 't2-intake-automation',
    tier: 2,
    category: 'intake',
    industries: ['professional-services'],
    title: 'Client intake automation (Clio Grow / Lawmatics style)',
    pitch: 'Lead form → intake questionnaire → engagement letter → first payment — all automated.',
    effort: 'Medium',
    setupHours: '10–14 hrs',
    cost: '$2,200 setup + $79+/mo',
    fixes: () => 'Every minute between "I need your help" and signed engagement letter is when the client can walk away. Automation compresses it from 3 days to 30 min.',
    roi: () => ({
      hoursPerWeek: 4,
      dollarsPerMonth: 4000,
      summary: '4 hrs/week back + higher intake close rate ≈ $4k/mo',
    }),
    whatYouGet: [
      'Intake questionnaire linked from your website',
      'Conflict check automation',
      'Engagement letter auto-generated with intake data',
      'E-signature via DocuSign / PandaDoc',
      'Retainer payment link embedded',
      'New matter automatically created in your practice management tool',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'professional-services',
    priority: () => 45,
  },
  {
    id: 't2-content-engine',
    tier: 2,
    category: 'content',
    industries: ['professional-services'],
    title: 'Content marketing engine (blog + LinkedIn)',
    pitch: 'Weekly educational post answering the questions prospects Google. Compounds into a lead machine.',
    effort: 'Medium',
    setupHours: '8 hrs setup + 4 hrs/mo',
    cost: '$1,500 setup + $900/mo retainer',
    fixes: (a) =>
      a.newClientFlow === 'referral-only'
        ? "You're 100% referral-dependent. One bad quarter and you're scrambling. Content builds an independent lead pipeline."
        : 'Consistent content is what separates practices with a waitlist from practices with a marketing budget.',
    roi: () => ({
      dollarsPerMonth: 6000,
      summary: 'Year-1 typical: 2 qualified new-client calls/mo from content ≈ $6k/mo new revenue',
    }),
    whatYouGet: [
      'Keyword research for your specialty + local area',
      '4 SEO-optimized blog posts per month',
      'LinkedIn repurposing for each',
      'Lead magnet (downloadable checklist/template)',
      'Monthly performance report',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'professional-services',
    priority: (a) => 35 + (a.newClientFlow === 'referral-only' ? 15 : 0),
  },
  {
    id: 't3-client-matter-portal',
    tier: 3,
    category: 'ops',
    industries: ['professional-services'],
    title: 'Custom client portal (matter status, docs, billing)',
    pitch: 'Your clients log in and see exactly where their matter stands. 50% fewer "any updates?" emails.',
    effort: 'Big',
    setupHours: '100–140 hrs',
    cost: '$14,000 build + $200/mo',
    priceAnchor: 'Typical: Clio Manage + Clio Grow stack ~$3k/yr + setup · This portal: $14k one-time',
    fixes: () => 'Clients interrupt your billable work with status questions. A portal replaces that with self-serve visibility.',
    roi: () => ({
      hoursPerWeek: 6,
      dollarsPerMonth: 5000,
      summary: '6 hrs/week of billable time recovered ≈ $5k/mo',
    }),
    whatYouGet: [
      'Branded client portal at portal.yourfirm.com',
      'Matter status + timeline view',
      'Secure document exchange (replaces email attachments)',
      'E-signature for amendments/addenda',
      'Billing view with pay-now button',
      'Mobile-friendly',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'professional-services' && teamSize(a) >= 2,
    priority: () => 30,
  },

  // B2B / SAAS
  {
    id: 't1-crm-hygiene',
    tier: 1,
    category: 'sales',
    industries: ['b2b-saas'],
    title: 'CRM hygiene + pipeline discipline',
    pitch: 'If your CRM is a graveyard of stale deals, no AI in the world fixes that. Start clean.',
    effort: 'Easy',
    setupHours: '4 hrs',
    cost: 'Free (inside HubSpot / Pipedrive / Close)',
    fixes: (a) =>
      a.crm === 'spreadsheet' || a.crm === 'none'
        ? "You're tracking deals in a spreadsheet (or not tracking). Your first lift is just getting into a real CRM."
        : 'Most CRMs are full of stale deals that poison your forecasting. Clean it up in an afternoon.',
    roi: () => ({
      hoursPerWeek: 2,
      dollarsPerMonth: 3000,
      summary: 'Cleaner pipeline = better forecasting + 5–10% win rate ≈ $3k/mo',
    }),
    diyGuide: {
      tools: ['Your CRM (HubSpot / Pipedrive / Close / Salesforce)'],
      steps: [
        'Close or archive deals untouched > 90 days',
        'Ensure every open deal has: next step, close date, dollar value',
        'Create saved views by stage so you see the pipeline at a glance',
        'Block 15 min/day for CRM updates — ritualize it',
        'Weekly review: anything without movement in 2 weeks, call or kill',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'b2b-saas',
    priority: () => 45,
  },
  {
    id: 't2-outbound-sequence',
    tier: 2,
    category: 'sales',
    industries: ['b2b-saas', 'professional-services'],
    title: 'Outbound sequence + meeting booker setup',
    pitch: 'Apollo / Instantly / Lemlist configured, sequences written, meetings hit your calendar.',
    effort: 'Medium',
    setupHours: '12–16 hrs',
    cost: '$2,500 setup + $150–$400/mo tooling',
    fixes: (a) =>
      a.primaryChannel === 'outbound'
        ? "You're running outbound but not at the cadence / personalization level the top 10% hit. Dial it in."
        : 'Add outbound as your 2nd channel — most founders start here and never leave.',
    roi: () => ({
      dollarsPerMonth: 8000,
      summary: 'Typical: 5–10 qualified meetings/mo at $10k ACV ≈ $8k/mo from pipeline (win-adjusted)',
    }),
    whatYouGet: [
      'ICP + persona definition',
      'List built in Apollo / LinkedIn Sales Navigator',
      '5-touch sequence (email + LinkedIn + call) written for your voice',
      'Calendly embedded in every email',
      'Reply tracking + A/B test rotation',
      'Weekly reporting for 30 days',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'b2b-saas',
    priority: (a) => 40 + (a.primaryChannel === 'outbound' ? 10 : 0),
  },
  {
    id: 't2-onboarding-flow',
    tier: 2,
    category: 'delivery',
    industries: ['b2b-saas'],
    title: 'User onboarding flow (in-app + email)',
    pitch: 'Good onboarding cuts 30-day churn in half. Users who reach "aha" in day 1 stick around.',
    effort: 'Medium',
    setupHours: '20–30 hrs',
    cost: '$3,500',
    fixes: (a) =>
      (a.churnRatePct ?? 0) > 0.05
        ? `Your ${Math.round((a.churnRatePct ?? 0) * 100)}% churn is eating your growth. Onboarding is the highest-leverage fix.`
        : 'Onboarding is usually the #1 churn lever before product-market fit and #2 after.',
    roi: () => ({
      dollarsPerMonth: 5000,
      summary: 'Halve early churn ≈ $5k/mo MRR retained',
    }),
    whatYouGet: [
      'User activation definition (the single event that predicts retention)',
      'In-app onboarding checklist with progress',
      '5-email onboarding sequence tied to product events',
      'Day-7 and Day-14 check-in automation',
      'Trial-end rescue flow',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'b2b-saas',
    priority: () => 45,
  },
  {
    id: 't3-revenue-ops-stack',
    tier: 3,
    category: 'ops',
    industries: ['b2b-saas'],
    title: 'Revenue ops stack (CRM + data + automation)',
    pitch: 'HubSpot + Clay + Apollo + Stripe + Attio — integrated into one source of truth.',
    effort: 'Big',
    setupHours: '100–160 hrs',
    cost: '$16,000 build + $400/mo tooling',
    priceAnchor: 'Typical RevOps hire: $130k+/yr · This system: $16k one-time',
    fixes: () => 'Every tool is a data island. Integrated, you get attribution, forecasting, and automation that actually works.',
    roi: () => ({
      hoursPerWeek: 10,
      dollarsPerMonth: 12000,
      summary: '10 hrs/week back on manual ops + 15% pipeline lift from better automation ≈ $12k/mo',
    }),
    whatYouGet: [
      'HubSpot / Salesforce configured with your ICP',
      'Clay / Apollo enriched lead pipeline',
      'Stripe / billing data pulled into CRM',
      'Lifecycle automation across email + in-app',
      'Executive dashboard: MRR, pipeline, cohort retention',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'b2b-saas' && (a.stage === '50k-500k-mrr' || a.stage === '500k-plus-mrr'),
    priority: () => 35,
  },

  // CREATIVE
  {
    id: 't1-deposit-policy',
    tier: 1,
    category: 'billing',
    industries: ['creative', 'project-based'],
    title: '50% deposit up front + milestone billing',
    pitch: 'Deposits filter serious clients and fund the work. Non-negotiable for solo creatives.',
    effort: 'Easy',
    setupHours: '30 min',
    cost: 'Free',
    fixes: () => "Without a deposit, you're financing the client's project. Switch to 50% up front today.",
    roi: () => ({
      hoursPerWeek: 0,
      dollarsPerMonth: 2500,
      summary: 'Faster cash cycle + no more ghost clients ≈ $2.5k/mo cash flow',
    }),
    diyGuide: {
      tools: ['Your contract + invoice template'],
      steps: [
        'Update your contract: "50% deposit due within 7 days of signing"',
        'No deposit = no project. Hold the calendar date until paid.',
        'For big projects (10k+): 50% deposit, 25% at mid-point milestone, 25% on delivery',
        'Final files do NOT go out until final payment clears',
        'Add a late-payment clause: 1.5% interest/mo after 30 days',
      ],
    },
    cta: null,
    triggers: (a) => a.industry === 'creative',
    priority: () => 40,
  },
  {
    id: 't2-asset-delivery-portal',
    tier: 2,
    category: 'delivery',
    industries: ['creative'],
    title: 'Branded client gallery + asset delivery (Pixieset / Pic-Time)',
    pitch: 'Clients see their gallery, favorite photos, order prints. You upsell without being pushy.',
    effort: 'Medium',
    setupHours: '3–5 hrs',
    cost: '$600 setup + $8–$30/mo',
    fixes: (a) =>
      a.assetDeliveryTool === 'dropbox' || a.assetDeliveryTool === 'wetransfer' || a.assetDeliveryTool === 'email'
        ? 'Dropbox/WeTransfer delivery is fine for files but awful for experience. A real gallery adds print sales + referrals.'
        : '',
    roi: () => ({
      dollarsPerMonth: 2500,
      summary: 'Print sales + upsells from gallery ≈ $2.5k/mo for a working photographer',
    }),
    whatYouGet: [
      'Pixieset / Pic-Time account configured',
      'Branded gallery template matching your look',
      'Print lab + pricing tier integration',
      'Client favoriting + sharing features',
      'Download permissions controlled per gallery',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'creative',
    priority: () => 35,
  },
  {
    id: 't2-contract-studio',
    tier: 2,
    category: 'billing',
    industries: ['creative'],
    title: 'Contract + invoice + booking studio (HoneyBook / Dubsado)',
    pitch: 'One platform for lead → contract → deposit → project → invoice → review. Replaces 5 apps.',
    effort: 'Medium',
    setupHours: '10–16 hrs',
    cost: '$1,600 setup + $30–$40/mo',
    fixes: () => 'Most creatives run 5+ tools loosely stitched together. HoneyBook/Dubsado unifies them in a single branded flow.',
    roi: () => ({
      hoursPerWeek: 5,
      dollarsPerMonth: 3500,
      summary: '5 hrs/week back + faster bookings ≈ $3.5k/mo',
    }),
    whatYouGet: [
      'HoneyBook or Dubsado configured with your packages',
      'Branded lead capture form on your site',
      'Contract + questionnaire + invoice templates',
      'Automated workflow: inquiry → proposal → contract → deposit',
      'Client portal for every project',
    ],
    cta: 'calendly-scope',
    triggers: (a) => a.industry === 'creative',
    priority: () => 40,
  },
  {
    id: 't3-creative-ops-app',
    tier: 3,
    category: 'ops',
    industries: ['creative'],
    title: 'Custom booking + delivery app for creatives',
    pitch: 'Your own branded app: booking → shoot day → gallery → print sales. One platform, not five.',
    effort: 'Big',
    setupHours: '80–120 hrs',
    cost: '$11,000 build + $200/mo',
    priceAnchor: 'Typical stack: HoneyBook + Pixieset + website + mailing list = $100+/mo forever · This app: $11k one-time',
    fixes: () => 'As a creative your brand IS the product. Off-the-shelf tools dilute your brand at every touchpoint.',
    roi: () => ({
      hoursPerWeek: 6,
      dollarsPerMonth: 4000,
      summary: '6 hrs/week back + higher-end brand positioning ≈ $4k/mo',
    }),
    whatYouGet: [
      'Branded web app at yourname.com',
      'Booking flow with package selection',
      'Contract + deposit + calendar confirmation',
      'Client portal for each project',
      'Gallery delivery + print sales',
      'iOS + Android native shells (optional)',
    ],
    cta: 'calendly-strategy',
    triggers: (a) => a.industry === 'creative' && teamSize(a) <= 3,
    priority: () => 30,
  },
]
