export interface Testimonial {
  name: string
  title: string
  text: string
}

export interface PortfolioItem {
  id: string
  demoSlug: string
  businessName: string
  tagline: string
  description: string
  features: string[]
  heroGradient: string
  accentColor: string
  services: string[]
  ctaLabel: string
  niche: 'contractors' | 'ecommerce' | 'real-estate' | 'law-firms'
  // Demo page content
  phone: string
  location: string
  heroHeadline: string
  heroSubtext: string
  testimonials: Testimonial[]
}

export const portfolioItems: PortfolioItem[] = [
  // Contractors
  {
    id: 'vanguard-roofing',
    demoSlug: 'vanguard-roofing',
    businessName: 'Vanguard Roofing Co.',
    tagline: 'Denver\'s most trusted roofers · Licensed & insured',
    description: 'Full-site rebuild for a local roofing company. Lead capture form, photo gallery, Google reviews integration, and fast-loading service area pages.',
    features: ['Lead Form', 'Service Area Pages', 'Photo Gallery', 'Google Reviews'],
    heroGradient: 'linear-gradient(135deg, #1a0a00 0%, #3d1a00 50%, #5c2800 100%)',
    accentColor: '#f97316',
    services: ['Roof Replacement', 'Repairs', 'Storm Damage', 'New Construction', 'Gutters', 'Inspections'],
    ctaLabel: 'Get a Free Estimate',
    niche: 'contractors',
    phone: '(555) 843-7200',
    location: 'Denver, CO',
    heroHeadline: "Denver's Most Trusted Roofing Contractor",
    heroSubtext: 'Licensed, insured, and backed by 25 years of roofing excellence. We handle everything from emergency repairs to full replacements — with a transferable warranty on every job.',
    testimonials: [
      { name: 'Marcus T.', title: 'Homeowner, Denver', text: 'Vanguard replaced our entire roof after the hailstorm last spring. Professional crew, clean work site, and finished in one day. Could not be happier.' },
      { name: 'Sarah K.', title: 'Property Manager', text: 'We manage 12 units and Vanguard is our go-to roofer. Responsive, priced fairly, and the work always holds up through the winters.' },
      { name: 'James & Linda F.', title: 'Homeowners, Littleton', text: "Got three quotes and Vanguard was the most transparent. No upsells, no surprises on the invoice. The new roof looks fantastic." },
    ],
  },
  {
    id: 'arcticbreeze-hvac',
    demoSlug: 'arcticbreeze-hvac',
    businessName: 'ArcticBreeze HVAC',
    tagline: 'Heating & cooling experts · 24/7 emergency service',
    description: 'Clean, conversion-focused site for an HVAC company with seasonal promotions, online booking teaser, and service area landing pages.',
    features: ['Booking CTA', 'Service Pages', 'Seasonal Promos', 'Local SEO'],
    heroGradient: 'linear-gradient(135deg, #001a2e 0%, #003359 50%, #004a80 100%)',
    accentColor: '#0ea5e9',
    services: ['AC Installation', 'Heating Systems', 'Tune-Ups & Maintenance', '24/7 Emergency', 'Ductwork', 'Air Quality'],
    ctaLabel: 'Schedule Service Today',
    niche: 'contractors',
    phone: '(555) 612-4800',
    location: 'Phoenix, AZ',
    heroHeadline: 'Stay Cool. Stay Warm. Stay Comfortable.',
    heroSubtext: "Phoenix's #1 rated HVAC company. Upfront pricing, no surprise fees, and technicians who show up on time. Emergency service available around the clock.",
    testimonials: [
      { name: 'David R.', title: 'Homeowner, Scottsdale', text: 'AC went out on a Friday at 4pm during a 115° day. ArcticBreeze had a tech at my house by 6pm and fixed it the same night. Lifesavers.' },
      { name: 'Priya M.', title: 'Office Manager', text: 'We had them install a new system for our 3,000 sq ft office. Clean install, no disruption to business, and our energy bill dropped 22%.' },
      { name: 'Tom & Carol B.', title: 'Homeowners, Mesa', text: 'The annual maintenance plan is worth every penny. They catch issues before they become expensive. Our 15-year-old unit is still running strong.' },
    ],
  },
  {
    id: 'ironflow-plumbing',
    demoSlug: 'ironflow-plumbing',
    businessName: 'IronFlow Plumbing',
    tagline: 'Fast, reliable plumbing · No hidden fees',
    description: 'Modern site for a plumbing company with clear pricing info, emergency callout banner, and a trust-building "our team" section.',
    features: ['Emergency Banner', 'Pricing FAQ', 'Team Section', 'Review Feed'],
    heroGradient: 'linear-gradient(135deg, #001e2e 0%, #003347 50%, #00526e 100%)',
    accentColor: '#0891b2',
    services: ['Drain Cleaning', 'Leak Detection & Repair', 'Water Heaters', 'Bathroom Remodels', 'Emergency Service', 'Pipe Replacement'],
    ctaLabel: "Call Now — We're Available",
    niche: 'contractors',
    phone: '(555) 771-3300',
    location: 'Austin, TX',
    heroHeadline: 'Fast, Reliable Plumbing — When You Need It Most',
    heroSubtext: "Austin's go-to plumbing pros. Emergency service, transparent pricing, and technicians who respect your home. We fix it right the first time — guaranteed.",
    testimonials: [
      { name: 'Rachel N.', title: 'Homeowner, South Austin', text: 'Pipe burst on a Sunday morning. IronFlow was at my house within 45 minutes. Fixed the leak, cleaned up, and the price was totally reasonable.' },
      { name: 'Greg P.', title: 'Restaurant Owner', text: 'They handle all plumbing for my two locations. Fast, reliable, and they understand the urgency when something breaks in a commercial kitchen.' },
      { name: 'Allison C.', title: 'Real Estate Agent', text: 'I refer IronFlow to every client who needs plumbing work before closing. Professional, honest assessments, and they never try to upsell.' },
    ],
  },
  {
    id: 'voltedge-electrical',
    demoSlug: 'voltedge-electrical',
    businessName: 'VoltEdge Electrical',
    tagline: 'Licensed electricians · Residential & commercial',
    description: 'Sharp, professional site for an electrical contractor with service pages, before/after project gallery, and a strong local SEO footprint.',
    features: ['Project Gallery', 'Service Pages', 'Local SEO', 'Contact Form'],
    heroGradient: 'linear-gradient(135deg, #0d0d00 0%, #262600 50%, #3d3900 100%)',
    accentColor: '#eab308',
    services: ['Panel Upgrades', 'Full Rewires', 'EV Chargers', 'Commercial Electrical', 'Lighting Design', 'Safety Inspections'],
    ctaLabel: 'Get a Free Quote',
    niche: 'contractors',
    phone: '(555) 924-6100',
    location: 'Seattle, WA',
    heroHeadline: 'Licensed Electricians for Every Job — Done Right, Done Safe',
    heroSubtext: "Seattle's trusted electrical contractors since 2003. From panel upgrades to full commercial rewires, we bring code-compliant workmanship and clear communication to every project.",
    testimonials: [
      { name: 'Kevin L.', title: 'Homeowner, Bellevue', text: 'Had VoltEdge install two EV chargers and upgrade our panel. Showed up exactly on time, explained everything, and left the garage cleaner than they found it.' },
      { name: 'Nina S.', title: 'Retail Store Owner', text: 'We needed a full electrical overhaul for our new location. VoltEdge handled permits, inspections, and the work itself. Zero stress on our end.' },
      { name: 'Brian W.', title: 'Homeowner, Capitol Hill', text: "Older home with sketchy wiring. VoltEdge did a full safety audit and re-wired the problem areas. Transparent pricing, no pressure, total pros." },
    ],
  },

  // E-Commerce
  {
    id: 'velvet-petal',
    demoSlug: 'velvet-petal',
    businessName: 'Velvet Petal Skincare',
    tagline: 'Clean beauty. Real results.',
    description: 'Shopify store for a premium skincare brand. Custom theme, product bundles, email capture popup, and a high-converting product page layout.',
    features: ['Custom Theme', 'Product Bundles', 'Email Capture', 'Upsell Flow'],
    heroGradient: 'linear-gradient(135deg, #1a0a1a 0%, #2d1040 50%, #3d1566 100%)',
    accentColor: '#c084fc',
    services: ['Cleansers', 'Serums', 'Moisturizers', 'Eye Care', 'Bundles', 'Gift Sets'],
    ctaLabel: 'Shop the Collection',
    niche: 'ecommerce',
    phone: '',
    location: '',
    heroHeadline: 'Clean Beauty, Formulated for Real Skin.',
    heroSubtext: 'Botanically sourced, dermatologist-tested, free from parabens and synthetic fragrance. Skincare that works with your skin, not against it.',
    testimonials: [
      { name: 'Olivia H.', title: 'Verified Customer', text: "The Hydrating Serum changed my skin completely. I've tried dozens of serums and nothing else has come close. I'm a customer for life." },
      { name: 'Maya R.', title: 'Verified Customer', text: 'Love that everything is clean and actually effective. The bundle deals are great value and the packaging is gorgeous — makes a perfect gift.' },
      { name: 'Chloe T.', title: 'Verified Customer', text: 'Finally a brand that delivers on its promises. My hyperpigmentation has faded noticeably in just 6 weeks of using the brightening routine.' },
    ],
  },
  {
    id: 'tailwag-supply',
    demoSlug: 'tailwag-supply',
    businessName: 'TailWag Supply Co.',
    tagline: 'Premium pet supplies · Free shipping over $50',
    description: 'Pet supplies Shopify store with category navigation, loyalty program teaser, and a breed-specific product filter built using Shopify metafields.',
    features: ['Category Nav', 'Product Filters', 'Loyalty Teaser', 'Bundle Deals'],
    heroGradient: 'linear-gradient(135deg, #0a1a08 0%, #143d10 50%, #1a5216 100%)',
    accentColor: '#22c55e',
    services: ['Dog Food & Treats', 'Cat Essentials', 'Toys & Play', 'Health & Wellness', 'Grooming', 'Accessories'],
    ctaLabel: 'Shop for Your Pet',
    niche: 'ecommerce',
    phone: '',
    location: '',
    heroHeadline: 'Everything Your Pet Deserves — Delivered to Your Door.',
    heroSubtext: "Premium food, toys, and accessories curated by pet owners for pet owners. Free shipping over $50. Easy returns. Your pet's happiness is our obsession.",
    testimonials: [
      { name: 'Amanda P.', title: 'Dog Mom, 2 Labs', text: 'Found TailWag through a recommendation and now I order everything here. The food selection is fantastic and shipping is always super fast.' },
      { name: 'Derek C.', title: 'Cat Dad', text: "My three cats are picky and they love everything I've gotten from TailWag. The subscription option for food is a huge timesaver." },
      { name: 'Sandra G.', title: 'Rescue Volunteer', text: 'We use TailWag for our rescue organization. The bulk discounts are generous and the customer service team is incredibly helpful.' },
    ],
  },
  {
    id: 'ember-wick-candles',
    demoSlug: 'ember-wick-candles',
    businessName: 'Ember & Wick Candles',
    tagline: 'Hand-poured artisan candles · Small batch, big mood.',
    description: 'Artisan candle brand store with a warm aesthetic, scent quiz landing page, seasonal collections, and subscription box integration.',
    features: ['Scent Quiz', 'Subscriptions', 'Seasonal Drops', 'Gift Wrapping'],
    heroGradient: 'linear-gradient(135deg, #1a0f00 0%, #2e1a00 50%, #453000 100%)',
    accentColor: '#f97316',
    services: ['Soy Candles', 'Wax Melts', 'Reed Diffusers', 'Gift Boxes', 'Seasonal Collections', 'Bulk Orders'],
    ctaLabel: 'Shop Candles',
    niche: 'ecommerce',
    phone: '',
    location: '',
    heroHeadline: 'Hand-Poured Candles That Fill Your Space With Soul.',
    heroSubtext: '100% soy wax, cotton wicks, and premium fragrance oils. Every candle is poured in small batches so you always get the freshest, most vibrant scent experience.',
    testimonials: [
      { name: 'Jessica M.', title: 'Verified Customer', text: "I've ordered from Ember & Wick three times now. The Sandalwood Cedar is my signature scent — everyone who comes over asks about it." },
      { name: 'Tyler B.', title: 'Gift Buyer', text: 'Ordered the gift box set for my mom and she absolutely loved it. Beautiful packaging, fast shipping, and the scents are incredible.' },
      { name: 'Lauren F.', title: 'Subscription Member', text: 'The monthly subscription is my favorite thing. Every month is a surprise and I\'ve discovered scents I never would have picked for myself.' },
    ],
  },
  {
    id: 'peakform-fitness',
    demoSlug: 'peakform-fitness',
    businessName: 'PeakForm Fitness Gear',
    tagline: 'Built for performance. Worn for life.',
    description: 'Fitness gear store with size guide pages, training program upsells, and a reviews section featuring athlete testimonials and user-submitted photos.',
    features: ['Size Guide', 'Review Feed', 'Training Upsell', 'Multi-currency'],
    heroGradient: 'linear-gradient(135deg, #0d0000 0%, #2a0000 50%, #400000 100%)',
    accentColor: '#ef4444',
    services: ['Performance Apparel', 'Training Equipment', 'Supplements', 'Accessories', 'Bundles', 'Recovery Gear'],
    ctaLabel: 'Shop Performance Gear',
    niche: 'ecommerce',
    phone: '',
    location: '',
    heroHeadline: 'Built for the Relentless. Worn by the Driven.',
    heroSubtext: "Performance apparel and equipment engineered for athletes who refuse to settle. Durable, functional, and designed to move with you — from warm-up to max effort.",
    testimonials: [
      { name: 'Chris D.', title: 'Competitive Powerlifter', text: "PeakForm's knee sleeves are the best I've ever used. Worn them through two national meets and they show zero wear. Worth every dollar." },
      { name: 'Kayla M.', title: 'CrossFit Coach', text: 'I recommend PeakForm to all my athletes. The quality is consistent, sizing is accurate, and the customer service actually helps when there\'s an issue.' },
      { name: 'Marcus J.', title: 'Marathon Runner', text: 'The compression gear has genuinely improved my recovery time. I was skeptical but the science checks out — and it holds up through serious mileage.' },
    ],
  },

  // Real Estate
  {
    id: 'meridian-luxury-realty',
    demoSlug: 'meridian-luxury-realty',
    businessName: 'Meridian Luxury Realty',
    tagline: 'Exceptional homes. Exceptional service.',
    description: 'High-end realtor site with IDX-style listing showcase, neighborhood guides, and a consultation booking flow that captures serious buyer leads.',
    features: ['Listing Showcase', 'Neighborhood Guides', 'Lead Forms', 'Market Reports'],
    heroGradient: 'linear-gradient(135deg, #0a0a00 0%, #1a1400 50%, #2a2200 100%)',
    accentColor: '#d4af37',
    services: ['Buyer Representation', 'Seller Representation', 'Luxury Homes', 'Relocation Services', 'Investment Properties', 'New Development'],
    ctaLabel: 'View Current Listings',
    niche: 'real-estate',
    phone: '(555) 847-2900',
    location: 'Scottsdale, AZ',
    heroHeadline: 'Extraordinary Homes for Extraordinary Lives.',
    heroSubtext: "Scottsdale's premier luxury real estate team. Whether you're buying, selling, or investing, we bring white-glove service and deep market expertise to every transaction.",
    testimonials: [
      { name: 'Jonathan & Claire V.', title: 'Luxury Buyers', text: "Meridian found us our dream home in Paradise Valley. They had access to off-market listings we couldn't find anywhere else. Seamless from start to close." },
      { name: 'Diane M.', title: 'Home Seller', text: 'Listed with Meridian and received three offers above asking within the first week. Their marketing is in a completely different league.' },
      { name: 'Robert S.', title: 'Investment Buyer', text: "I've done four transactions with Meridian now. Their knowledge of the luxury market is unmatched and they always protect my interests." },
    ],
  },
  {
    id: 'keystone-property',
    demoSlug: 'keystone-property',
    businessName: 'Keystone Property Group',
    tagline: 'Stress-free property management · Full service.',
    description: 'Property management company site with separate owner and tenant portals, vacancy listing feed, and a clear services breakdown with pricing tiers.',
    features: ['Owner Portal CTA', 'Tenant Portal', 'Vacancy Feed', 'Services Breakdown'],
    heroGradient: 'linear-gradient(135deg, #050d1a 0%, #0a1f3d 50%, #102d5c 100%)',
    accentColor: '#3b82f6',
    services: ['Tenant Screening', 'Rent Collection', 'Maintenance Coordination', 'Financial Reporting', 'Leasing', 'Eviction Support'],
    ctaLabel: 'Get a Free Management Quote',
    niche: 'real-estate',
    phone: '(555) 634-8100',
    location: 'Chicago, IL',
    heroHeadline: 'Professional Property Management, Completely Simplified.',
    heroSubtext: "Full-service property management for Chicago landlords. We handle tenant screening, rent collection, maintenance, and monthly reporting — so you can enjoy passive income without the headaches.",
    testimonials: [
      { name: 'Patricia L.', title: '8-Unit Landlord', text: 'Switched to Keystone after self-managing for 5 years. The difference is night and day. Zero vacancies in 14 months and I never get late-night maintenance calls anymore.' },
      { name: 'Ahmed K.', title: 'Investor, 3 Properties', text: "Their financial reporting is incredibly clear. I always know exactly what my properties are earning and where every dollar is going." },
      { name: 'Stacy B.', title: 'Out-of-State Owner', text: 'I own two units in Chicago and live in Florida. Keystone handles everything. I literally get a deposit every month and a clean monthly report. Could not be easier.' },
    ],
  },
  {
    id: 'compass-point-homes',
    demoSlug: 'compass-point-homes',
    businessName: 'Compass Point Homes',
    tagline: 'Boutique real estate. Personal attention.',
    description: 'Boutique agency site focused on personal branding for a small team of agents. Features agent bios, a sold portfolio section, and a home valuation CTA.',
    features: ['Agent Bios', 'Sold Portfolio', 'Home Valuation CTA', 'Community Pages'],
    heroGradient: 'linear-gradient(135deg, #1a0a0f 0%, #2d0f1a 50%, #3d152a 100%)',
    accentColor: '#ec4899',
    services: ['Home Buyers', 'Home Sellers', 'Rentals', 'Home Staging Advice', 'Relocation', 'First-Time Buyers'],
    ctaLabel: 'Find Your Direction Home',
    niche: 'real-estate',
    phone: '(555) 719-5500',
    location: 'Nashville, TN',
    heroHeadline: 'Find Your Direction Home in Nashville.',
    heroSubtext: "Nashville's boutique real estate team. Personalized service, neighborhood-level expertise, and results that speak for themselves. We work with fewer clients so we can give each one our full attention.",
    testimonials: [
      { name: 'Tyler & Meg S.', title: 'First-Time Buyers', text: 'Being first-time buyers, we were nervous. Our agent at Compass Point walked us through every step patiently. We found our home in 3 weeks and the process was actually fun.' },
      { name: 'Vanessa O.', title: 'Home Seller', text: 'Sold in 6 days at 4% over asking. Their staging advice made a real difference. Professional photography, great social media exposure — the whole package.' },
      { name: 'Derek H.', title: 'Relocation Buyer', text: "Relocated from Boston and had never lived in Nashville. The neighborhood tours and community guides Compass Point provided were invaluable. Couldn't have done it without them." },
    ],
  },
  {
    id: 'steelbridge-commercial',
    demoSlug: 'steelbridge-commercial',
    businessName: 'Steelbridge Commercial',
    tagline: 'Office. Retail. Industrial. We know commercial.',
    description: 'Commercial real estate site with property type filters, CoStar-style listing cards, and a lead intake form tailored for business owner inquiries.',
    features: ['Property Filters', 'Listing Cards', 'Business Lead Form', 'Market Insights'],
    heroGradient: 'linear-gradient(135deg, #050a0f 0%, #0d1a24 50%, #162a36 100%)',
    accentColor: '#06b6d4',
    services: ['Office Space', 'Retail Leasing', 'Industrial & Warehouse', 'Investment Sales', 'Tenant Rep', 'Site Selection'],
    ctaLabel: 'Browse Available Properties',
    niche: 'real-estate',
    phone: '(555) 388-7700',
    location: 'Houston, TX',
    heroHeadline: 'Commercial Real Estate Built on Relationships.',
    heroSubtext: "Helping Houston businesses find, lease, and invest in commercial properties since 2001. From small retail suites to large industrial facilities — we know this market inside out.",
    testimonials: [
      { name: 'Frank T.', title: 'Retail Business Owner', text: "Steelbridge found us our second location in a high-traffic corridor we never would have identified on our own. The deal they negotiated saved us $40k in the first year." },
      { name: 'Carol & James R.', title: 'Commercial Investors', text: 'We\'ve completed three investment purchases through Steelbridge. Their market insights are data-driven and their relationships with sellers are unmatched in Houston.' },
      { name: 'Ian B.', title: 'Manufacturing Company CEO', text: 'Needed 60,000 sq ft of industrial space on a tight timeline. Steelbridge had three viable options in front of us within a week. Professional, fast, effective.' },
    ],
  },

  // Law Firms
  {
    id: 'ashford-drake',
    demoSlug: 'ashford-drake',
    businessName: 'Ashford & Drake LLP',
    tagline: 'Personal injury attorneys fighting for you.',
    description: 'High-converting personal injury firm site with case value calculator, free consultation CTA above the fold, and Google review testimonials.',
    features: ['Case Calculator', 'Free Consult CTA', 'Review Feed', 'Practice Areas'],
    heroGradient: 'linear-gradient(135deg, #0d0000 0%, #1f0000 50%, #300000 100%)',
    accentColor: '#dc2626',
    services: ['Car & Truck Accidents', 'Slip & Fall', 'Workplace Injuries', 'Medical Malpractice', 'Wrongful Death', 'Product Liability'],
    ctaLabel: 'Get Your Free Case Review',
    niche: 'law-firms',
    phone: '(555) 556-4400',
    location: 'Atlanta, GA',
    heroHeadline: 'Injured? We Fight Until You Win.',
    heroSubtext: "Atlanta's most aggressive personal injury firm. No fees unless we win. Free case review within 24 hours. When insurance companies play hardball, Ashford & Drake plays harder.",
    testimonials: [
      { name: 'Terrence W.', title: 'Car Accident Client', text: 'After my accident, the insurance company offered me a lowball settlement. Ashford & Drake took the case and got me 7x what was offered. They are absolutely the best.' },
      { name: 'Maria G.', title: 'Slip & Fall Client', text: 'I was seriously injured at a grocery store and didn\'t know what to do. They handled everything, kept me informed, and got a settlement that covered all my medical bills and then some.' },
      { name: 'Kevin N.', title: 'Workplace Injury Client', text: "Don't try to navigate a serious injury claim alone. I tried and got nowhere. Ashford & Drake stepped in and the difference was immediate. Highly recommend." },
    ],
  },
  {
    id: 'cedarwood-family-law',
    demoSlug: 'cedarwood-family-law',
    businessName: 'Cedarwood Family Law',
    tagline: 'Compassionate family law attorneys.',
    description: 'Warm, approachable family law firm site with empathetic copy, practice area breakdowns, attorney bios, and a secure online consultation form.',
    features: ['Attorney Bios', 'Practice Areas', 'Consultation Form', 'Resource Blog'],
    heroGradient: 'linear-gradient(135deg, #050d1f 0%, #0b1f45 50%, #122e66 100%)',
    accentColor: '#60a5fa',
    services: ['Divorce & Separation', 'Child Custody', 'Adoption', 'Prenuptial Agreements', 'Mediation', 'Restraining Orders'],
    ctaLabel: 'Schedule a Consultation',
    niche: 'law-firms',
    phone: '(555) 673-2200',
    location: 'Portland, OR',
    heroHeadline: 'Protecting Families Through Life\'s Hardest Moments.',
    heroSubtext: 'Compassionate, experienced family law attorneys in Portland. We understand the emotional weight of these decisions and fight to protect what matters most — your family.',
    testimonials: [
      { name: 'Anonymous', title: 'Divorce Client', text: 'Going through a divorce is devastating. Cedarwood handled my case with real compassion while being incredibly effective. I felt supported every step of the way.' },
      { name: 'Rachel A.', title: 'Custody Client', text: "My children's wellbeing was on the line and Cedarwood never let me forget that's what mattered. We got the custody arrangement that was right for my kids." },
      { name: 'Daniel & Fiona S.', title: 'Adoption Clients', text: 'Cedarwood guided us through a complex adoption process with patience and expertise. We now have our daughter home and can\'t thank them enough.' },
    ],
  },
  {
    id: 'ironclad-defense',
    demoSlug: 'ironclad-defense',
    businessName: 'Ironclad Defense Group',
    tagline: 'Aggressive criminal defense. Proven results.',
    description: 'Authoritative criminal defense firm with prominently featured case results, 24/7 emergency call CTA, and a bail information resource section.',
    features: ['Case Results', '24/7 Emergency CTA', 'Bail Guide', 'Attorney Bio'],
    heroGradient: 'linear-gradient(135deg, #050508 0%, #0d0d12 50%, #14141e 100%)',
    accentColor: '#a78bfa',
    services: ['DUI & DWI', 'Drug Charges', 'Assault & Battery', 'Federal Crimes', 'Expungement', 'White Collar Crime'],
    ctaLabel: 'Call 24/7 — Free Case Review',
    niche: 'law-firms',
    phone: '(555) 900-2400',
    location: 'Las Vegas, NV',
    heroHeadline: 'Charged With a Crime? Call Ironclad Now.',
    heroSubtext: "Las Vegas's most aggressive criminal defense attorneys. Available 24/7 — because charges don't wait for business hours. Your freedom is our singular priority.",
    testimonials: [
      { name: 'Anonymous', title: 'DUI Client', text: 'I called Ironclad from the side of the road. They picked up immediately, walked me through everything, and ultimately got my charges reduced. Couldn\'t ask for more.' },
      { name: 'Robert T.', title: 'Drug Charges Client', text: "Facing federal drug charges is terrifying. Ironclad's team was relentless in building my defense. The outcome was better than I ever dared hope for." },
      { name: 'Anonymous', title: 'Assault Client', text: "I was falsely accused and felt powerless. Ironclad took my case seriously from day one and proved my innocence. They're in a different class from other firms I consulted." },
    ],
  },
  {
    id: 'summit-corporate',
    demoSlug: 'summit-corporate',
    businessName: 'Summit Corporate Counsel',
    tagline: 'Corporate & business legal counsel.',
    description: 'Polished corporate law firm site with industry-specific service pages, an attorney team section, and an intake form designed for business clients.',
    features: ['Industry Pages', 'Team Section', 'Business Intake Form', 'Legal Blog'],
    heroGradient: 'linear-gradient(135deg, #030710 0%, #07122a 50%, #0c1e45 100%)',
    accentColor: '#d4af37',
    services: ['Business Formation', 'Contract Drafting & Review', 'Mergers & Acquisitions', 'IP Protection', 'Employment Law', 'Regulatory Compliance'],
    ctaLabel: 'Request Business Counsel',
    niche: 'law-firms',
    phone: '(555) 441-8900',
    location: 'New York, NY',
    heroHeadline: 'Legal Counsel Serious Businesses Can Rely On.',
    heroSubtext: "NYC's trusted corporate law firm for startups, scaling companies, and established enterprises. Contracts, M&A, IP, and compliance — handled with precision at every stage of growth.",
    testimonials: [
      { name: 'Natasha P.', title: 'Startup Founder', text: "Summit handled our seed round documents, employment agreements, and IP filing all in the same month. Organized, fast, and thorough. The best legal partner we've had." },
      { name: 'William K.', title: 'CEO, Mid-Market Company', text: "We've used Summit for four acquisitions. They are detail-oriented, proactive about risk, and understand the commercial realities of deals — not just the legal ones." },
      { name: 'Amy H.', title: 'HR Director', text: 'Summit revamped all of our employment contracts and HR policies to ensure compliance. Process was fast, thorough, and they translated the legalese into plain English.' },
    ],
  },
]

export const portfolioByNiche = {
  contractors: portfolioItems.filter((i) => i.niche === 'contractors'),
  ecommerce: portfolioItems.filter((i) => i.niche === 'ecommerce'),
  'real-estate': portfolioItems.filter((i) => i.niche === 'real-estate'),
  'law-firms': portfolioItems.filter((i) => i.niche === 'law-firms'),
}

export const nichePortfolioMeta = {
  contractors: {
    label: 'Contractors & Trades',
    tagline: 'Lead-generating sites for roofers, HVAC, plumbers, electricians, and more.',
    color: '#f97316',
    serviceHref: '/services/contractors',
  },
  ecommerce: {
    label: 'E-Commerce Stores',
    tagline: 'Shopify stores that sell — from skincare to pet supplies to fitness gear.',
    color: '#22c55e',
    serviceHref: '/services/ecommerce',
  },
  'real-estate': {
    label: 'Realtors & Real Estate',
    tagline: 'Professional sites for luxury realtors, property managers, and boutique agencies.',
    color: '#d4af37',
    serviceHref: '/services/real-estate',
  },
  'law-firms': {
    label: 'Law Firms & Attorneys',
    tagline: 'Authoritative sites for personal injury, family law, criminal defense, and more.',
    color: '#60a5fa',
    serviceHref: '/services/law-firms',
  },
}
