export interface PortfolioItem {
  id: string
  businessName: string
  domain: string
  tagline: string
  description: string
  features: string[]
  heroGradient: string
  accentColor: string
  services: string[]
  ctaLabel: string
  niche: 'contractors' | 'ecommerce' | 'real-estate' | 'law-firms'
}

export const portfolioItems: PortfolioItem[] = [
  // Contractors
  {
    id: 'summit-roofing',
    businessName: 'Summit Roofing Co.',
    domain: 'summitroofingco',
    tagline: 'Trusted roofing since 1998 · Licensed & Insured',
    description: 'Full-site rebuild for a local roofing company. Lead capture form, photo gallery, Google reviews integration, and fast-loading service area pages.',
    features: ['Lead Form', 'Service Area Pages', 'Photo Gallery', 'Google Reviews'],
    heroGradient: 'linear-gradient(135deg, #1a0a00 0%, #3d1a00 50%, #5c2800 100%)',
    accentColor: '#f39c12',
    services: ['Roof Replacement', 'Repairs', 'Storm Damage', 'Inspections', 'Gutters'],
    ctaLabel: 'Get a Free Estimate',
    niche: 'contractors',
  },
  {
    id: 'arctic-air-hvac',
    businessName: 'Arctic Air HVAC',
    domain: 'arcticairhvac',
    tagline: 'Heating & cooling experts · 24/7 emergency service',
    description: 'Clean, conversion-focused site for an HVAC company with seasonal promotions, online booking teaser, and service area landing pages.',
    features: ['Booking CTA', 'Service Pages', 'Seasonal Promos', 'Local SEO'],
    heroGradient: 'linear-gradient(135deg, #001a2e 0%, #003359 50%, #004a80 100%)',
    accentColor: '#00cec9',
    services: ['AC Install', 'Heating', 'Tune-Ups', 'Emergency', 'Ductwork'],
    ctaLabel: 'Schedule Service',
    niche: 'contractors',
  },
  {
    id: 'proflow-plumbing',
    businessName: 'ProFlow Plumbing',
    domain: 'proflowplumbing',
    tagline: 'Fast, reliable plumbing · No hidden fees',
    description: 'Modern site for a plumbing company with clear pricing info, emergency callout banner, and a trust-building "our team" section.',
    features: ['Emergency Banner', 'Pricing FAQ', 'Team Section', 'Review Feed'],
    heroGradient: 'linear-gradient(135deg, #001e2e 0%, #003347 50%, #00526e 100%)',
    accentColor: '#0984e3',
    services: ['Drain Cleaning', 'Leak Repair', 'Water Heaters', 'Remodels', 'Emergency'],
    ctaLabel: "Call Now — We're Available",
    niche: 'contractors',
  },
  {
    id: 'volt-electric',
    businessName: 'Volt Electric LLC',
    domain: 'voltelectricllc',
    tagline: 'Licensed electricians · Residential & commercial',
    description: 'Sharp, professional site for an electrical contractor with service pages, before/after project gallery, and a strong local SEO footprint.',
    features: ['Project Gallery', 'Service Pages', 'Local SEO', 'Contact Form'],
    heroGradient: 'linear-gradient(135deg, #0d0d00 0%, #262600 50%, #3d3900 100%)',
    accentColor: '#f1c40f',
    services: ['Panel Upgrades', 'Rewiring', 'EV Chargers', 'Commercial', 'Inspections'],
    ctaLabel: 'Get a Free Quote',
    niche: 'contractors',
  },

  // E-Commerce
  {
    id: 'lumina-glow',
    businessName: 'Lumina Glow',
    domain: 'luminaglow',
    tagline: 'Clean skincare. Real results.',
    description: 'Shopify store for a premium skincare brand. Custom theme, product bundles, email capture popup, and a high-converting product page layout.',
    features: ['Custom Theme', 'Product Bundles', 'Email Capture', 'Upsell Flow'],
    heroGradient: 'linear-gradient(135deg, #1a0a1a 0%, #2d1040 50%, #3d1566 100%)',
    accentColor: '#d6a8ff',
    services: ['Serums', 'Moisturizers', 'Bundles', 'Gift Sets', 'Subscriptions'],
    ctaLabel: 'Shop the Collection',
    niche: 'ecommerce',
  },
  {
    id: 'pawsome-supply',
    businessName: 'Pawsome Supply Co.',
    domain: 'pawsomesupply',
    tagline: 'Premium pet supplies · Free shipping over $50',
    description: 'Pet supplies Shopify store with category navigation, loyalty program teaser, and a breed-specific product filter built using Shopify metafields.',
    features: ['Category Nav', 'Product Filters', 'Loyalty Teaser', 'Bundle Deals'],
    heroGradient: 'linear-gradient(135deg, #0a1a08 0%, #143d10 50%, #1a5216 100%)',
    accentColor: '#00b894',
    services: ['Dog Food', 'Cat Supplies', 'Toys', 'Health & Wellness', 'Accessories'],
    ctaLabel: 'Shop for Your Pet',
    niche: 'ecommerce',
  },
  {
    id: 'ember-and-wick',
    businessName: 'Ember & Wick',
    domain: 'emberandwick',
    tagline: 'Hand-poured artisan candles · Small batch, big mood.',
    description: 'Artisan candle brand store with a warm aesthetic, scent quiz landing page, seasonal collections, and subscription box integration.',
    features: ['Scent Quiz', 'Subscriptions', 'Seasonal Drops', 'Gift Wrapping'],
    heroGradient: 'linear-gradient(135deg, #1a0f00 0%, #2e1a00 50%, #453000 100%)',
    accentColor: '#e17055',
    services: ['Soy Candles', 'Wax Melts', 'Reed Diffusers', 'Gift Boxes', 'Bulk Orders'],
    ctaLabel: 'Shop Candles',
    niche: 'ecommerce',
  },
  {
    id: 'forgefit',
    businessName: 'ForgeFit Gear',
    domain: 'forgefitgear',
    tagline: 'Built for performance. Worn for life.',
    description: 'Fitness gear store with size guide pages, training program upsells, and a reviews section featuring athlete testimonials and user-submitted photos.',
    features: ['Size Guide', 'Review Feed', 'Training Upsell', 'Multi-currency'],
    heroGradient: 'linear-gradient(135deg, #0d0000 0%, #2a0000 50%, #400000 100%)',
    accentColor: '#d63031',
    services: ['Apparel', 'Equipment', 'Supplements', 'Accessories', 'Bundles'],
    ctaLabel: 'Shop Performance Gear',
    niche: 'ecommerce',
  },

  // Real Estate
  {
    id: 'meridian-luxury',
    businessName: 'Meridian Luxury Properties',
    domain: 'meridianluxury',
    tagline: 'Exceptional homes. Exceptional service.',
    description: 'High-end realtor site with IDX-style listing showcase, neighborhood guides, and a consultation booking flow that captures serious buyer leads.',
    features: ['Listing Showcase', 'Neighborhood Guides', 'Lead Forms', 'Market Reports'],
    heroGradient: 'linear-gradient(135deg, #0a0a00 0%, #1a1400 50%, #2a2200 100%)',
    accentColor: '#d4af37',
    services: ['Buyer Rep', 'Seller Rep', 'Luxury Homes', 'Relocation', 'Investment'],
    ctaLabel: 'View Current Listings',
    niche: 'real-estate',
  },
  {
    id: 'apex-property-mgmt',
    businessName: 'Apex Property Management',
    domain: 'apexpropertymgmt',
    tagline: 'Stress-free property management · Full service.',
    description: 'Property management company site with separate owner and tenant portals, vacancy listing feed, and a clear services breakdown with pricing tiers.',
    features: ['Owner Portal CTA', 'Tenant Portal', 'Vacancy Feed', 'Services Breakdown'],
    heroGradient: 'linear-gradient(135deg, #050d1a 0%, #0a1f3d 50%, #102d5c 100%)',
    accentColor: '#4a90e2',
    services: ['Tenant Screening', 'Rent Collection', 'Maintenance', 'Reporting', 'Leasing'],
    ctaLabel: 'Get a Free Management Quote',
    niche: 'real-estate',
  },
  {
    id: 'bloom-realty',
    businessName: 'Bloom & Co. Realty',
    domain: 'bloomcorealty',
    tagline: 'Boutique real estate. Personal attention.',
    description: 'Boutique agency site focused on personal branding for a small team of agents. Features agent bios, a sold portfolio section, and a home valuation CTA.',
    features: ['Agent Bios', 'Sold Portfolio', 'Home Valuation CTA', 'Community Pages'],
    heroGradient: 'linear-gradient(135deg, #1a0a0f 0%, #2d0f1a 50%, #3d152a 100%)',
    accentColor: '#e84393',
    services: ['Buyers', 'Sellers', 'Rentals', 'Staging', 'Relocation'],
    ctaLabel: 'Find Your Dream Home',
    niche: 'real-estate',
  },
  {
    id: 'summit-commercial',
    businessName: 'Summit Commercial RE',
    domain: 'summitcommercialre',
    tagline: 'Office. Retail. Industrial. We know commercial.',
    description: 'Commercial real estate site with property type filters, CoStar-style listing cards, and a lead intake form tailored for business owner inquiries.',
    features: ['Property Filters', 'Listing Cards', 'Business Lead Form', 'Market Insights'],
    heroGradient: 'linear-gradient(135deg, #050a0f 0%, #0d1a24 50%, #162a36 100%)',
    accentColor: '#00b4d8',
    services: ['Office Space', 'Retail', 'Industrial', 'Investment Sales', 'Leasing'],
    ctaLabel: 'Browse Commercial Properties',
    niche: 'real-estate',
  },

  // Law Firms
  {
    id: 'vega-law',
    businessName: 'Vega Law Group',
    domain: 'vegalawgroup',
    tagline: 'Personal injury attorneys fighting for you.',
    description: 'High-converting personal injury firm site with case value calculator, free consultation CTA above the fold, and Google review testimonials.',
    features: ['Case Calculator', 'Free Consult CTA', 'Review Feed', 'Practice Areas'],
    heroGradient: 'linear-gradient(135deg, #0d0000 0%, #1f0000 50%, #300000 100%)',
    accentColor: '#c0392b',
    services: ['Car Accidents', 'Slip & Fall', 'Work Injuries', 'Medical Malpractice', 'Wrongful Death'],
    ctaLabel: 'Get Your Free Case Review',
    niche: 'law-firms',
  },
  {
    id: 'hartley-family-law',
    businessName: 'Hartley Family Law',
    domain: 'hartleyfamilylaw',
    tagline: 'Compassionate family law attorneys.',
    description: 'Warm, approachable family law firm site with empathetic copy, practice area breakdowns, attorney bios, and a secure online consultation form.',
    features: ['Attorney Bios', 'Practice Areas', 'Consultation Form', 'Resource Blog'],
    heroGradient: 'linear-gradient(135deg, #050d1f 0%, #0b1f45 50%, #122e66 100%)',
    accentColor: '#3498db',
    services: ['Divorce', 'Child Custody', 'Adoption', 'Prenuptial Agreements', 'Mediation'],
    ctaLabel: 'Schedule a Consultation',
    niche: 'law-firms',
  },
  {
    id: 'stone-defense',
    businessName: 'Stone Defense Group',
    domain: 'stonedefensegroup',
    tagline: 'Aggressive criminal defense. Proven results.',
    description: 'Authoritative criminal defense firm with prominently featured case results, 24/7 emergency call CTA, and a bail information resource section.',
    features: ['Case Results', '24/7 Emergency CTA', 'Bail Guide', 'Attorney Bio'],
    heroGradient: 'linear-gradient(135deg, #050508 0%, #0d0d12 50%, #14141e 100%)',
    accentColor: '#a29bfe',
    services: ['DUI/DWI', 'Drug Charges', 'Assault', 'Federal Cases', 'Expungement'],
    ctaLabel: 'Call 24/7 — Free Case Review',
    niche: 'law-firms',
  },
  {
    id: 'pinnacle-business-law',
    businessName: 'Pinnacle Business Law',
    domain: 'pinnaclebusinesslaw',
    tagline: 'Corporate & business legal counsel.',
    description: 'Polished corporate law firm site with industry-specific service pages, an attorney team section, and an intake form designed for business clients.',
    features: ['Industry Pages', 'Team Section', 'Business Intake Form', 'Legal Blog'],
    heroGradient: 'linear-gradient(135deg, #030710 0%, #07122a 50%, #0c1e45 100%)',
    accentColor: '#d4af37',
    services: ['Business Formation', 'Contracts', 'M&A', 'IP Protection', 'Employment Law'],
    ctaLabel: 'Request Business Counsel',
    niche: 'law-firms',
  },
]

export const portfolioByNiche = {
  contractors: portfolioItems.filter((i) => i.niche === 'contractors'),
  ecommerce: portfolioItems.filter((i) => i.niche === 'ecommerce'),
  'real-estate': portfolioItems.filter((i) => i.niche === 'real-estate'),
  'law-firms': portfolioItems.filter((i) => i.niche === 'law-firms'),
}

export const nichePortfolioMeta = {
  contractors: {
    label: 'Contractors & Trades',
    tagline: 'Lead-generating sites for roofers, HVAC, plumbers, electricians, and more.',
    color: '#f39c12',
    serviceHref: '/services/contractors',
  },
  ecommerce: {
    label: 'E-Commerce Stores',
    tagline: 'Shopify stores that sell — from skincare to pet supplies to fitness gear.',
    color: '#00cec9',
    serviceHref: '/services/ecommerce',
  },
  'real-estate': {
    label: 'Realtors & Real Estate',
    tagline: 'Professional sites for luxury realtors, property managers, and boutique agencies.',
    color: '#6c5ce7',
    serviceHref: '/services/real-estate',
  },
  'law-firms': {
    label: 'Law Firms & Attorneys',
    tagline: 'Authoritative sites for personal injury, family law, criminal defense, and more.',
    color: '#0984e3',
    serviceHref: '/services/law-firms',
  },
}
