export const NICHE_PRICES = {
  contractors: {
    id: 'contractors',
    name: 'Contractors & Trades',
    slug: 'contractors',
    headline: 'A contractor website that generates leads — built, hosted, and maintained for you.',
    subheadline: 'Stop losing jobs to competitors with better websites. We build professional contractor sites that convert visitors into booked work.',
    problem: "You're great at your trade — not at managing websites. Figuring out hosting, SSL, slow mobile pages, and why your contact form stopped working shouldn't be part of your job.",
    icon: '🔨',
    color: '#f39c12',
    tiers: {
      basic: {
        name: 'Starter Lead Page',
        price: 149,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_BASIC || 'price_placeholder',
        features: [
          '1 landing page',
          'Contact & quote request form',
          'Photo/work gallery',
          'Basic on-page SEO',
          'Mobile optimized',
          'Google Maps embed',
          '+ Choose a hosting plan below',
        ],
      },
      standard: {
        name: 'Local Service Website',
        price: 399,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_STANDARD || 'price_placeholder',
        features: [
          'Up to 5 pages',
          'Lead form with photo upload',
          'Testimonials & reviews section',
          'Service area pages',
          'Speed optimization',
          'Google Business Profile setup',
          'Handoff checklist',
          '+ Choose a hosting plan below',
        ],
        popular: true,
      },
      premium: {
        name: 'Lead Engine + Trust Build',
        price: 799,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_PREMIUM || 'price_placeholder',
        features: [
          'Up to 10 pages + 3 service pages',
          'Conversion-optimized copywriting',
          'Schema markup (rich results)',
          'Google Analytics setup',
          'Before/after project gallery',
          'Emergency service CTA',
          '14-day post-launch support',
          '+ Choose a hosting plan below',
        ],
      },
    },
    faq: [
      { q: 'How long does it take to build my site?', a: 'Most contractor sites are live within 7–14 days after your onboarding call. Premium builds may take up to 21 days.' },
      { q: 'Do I need to provide content and photos?', a: "We'll guide you through a simple onboarding questionnaire. You provide your logo, photos of your work, and key business details — we handle the rest, including writing your copy." },
      { q: 'What if I already have a domain?', a: "No problem. We'll configure your existing domain to point to your new site. If you need a domain, we can register one for you." },
      { q: 'Can I make changes to my site?', a: 'Minor content updates (text, photos, hours) are included in your hosting plan. Major changes like new pages are available at a discounted hourly rate.' },
    ],
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-Commerce Stores',
    slug: 'ecommerce',
    headline: 'A Shopify store that sells — built, launched, and managed for you.',
    subheadline: 'Your competitors are converting visitors. We build Shopify stores optimized for sales, then manage them so you can focus on your products.',
    problem: "Setting up Shopify sounds simple until you're 4 hours deep trying to configure shipping zones, payment gateways, and theme settings. Then your sales are live but the store looks generic and converts at 1%.",
    icon: '🛍️',
    color: '#00cec9',
    tiers: {
      basic: {
        name: 'Starter Store Setup',
        price: 199,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_BASIC || 'price_placeholder',
        features: [
          'Shopify setup & theme config',
          'Up to 10 products loaded',
          'Payment gateway setup',
          'Shipping zone configuration',
          'Mobile optimization',
          'Basic branding applied',
          '+ Choose a hosting plan below',
        ],
      },
      standard: {
        name: 'Branded Store Launch',
        price: 549,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_STANDARD || 'price_placeholder',
        features: [
          'Custom branded Shopify theme',
          'Up to 50 products loaded',
          'Email capture + welcome flow',
          'Speed & conversion optimization',
          'SEO foundation (meta, sitemap)',
          'Social proof elements',
          'Abandoned cart recovery',
          '+ Choose a hosting plan below',
        ],
        popular: true,
      },
      premium: {
        name: 'CRO Rebuild + Launch Support',
        price: 1199,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_PREMIUM || 'price_placeholder',
        features: [
          'Full CRO-optimized redesign',
          'Unlimited products',
          'Upsell & cross-sell flows',
          'Post-purchase email sequences',
          'Google Analytics + Meta Pixel',
          'Loyalty/referral app setup',
          '30-day post-launch support',
          '+ Choose a hosting plan below',
        ],
      },
    },
    faq: [
      { q: 'Do I need an existing Shopify account?', a: 'No. We set everything up from scratch. You will need a Shopify subscription (starting at $39/mo directly with Shopify) — this is separate from our build and hosting fees.' },
      { q: 'How long until my store is live?', a: 'Starter builds typically 5–10 days. Standard 10–14 days. Premium 14–21 days after onboarding.' },
      { q: 'What\'s included in managed Shopify maintenance?', a: 'We handle theme updates, app compatibility, minor content changes, and troubleshooting. Your store stays current and working without you touching the backend.' },
      { q: 'Can you migrate my existing store?', a: 'Yes — product migration from existing stores is available. Contact us for a custom quote if you have more than 50 products.' },
    ],
  },
  'real-estate': {
    id: 'real-estate',
    name: 'Realtors & Real Estate',
    slug: 'real-estate',
    headline: 'A real estate website that captures leads — built, hosted, and maintained for you.',
    subheadline: 'Buyers and sellers Google their agent before they call. We build real estate sites that establish credibility and capture serious leads.',
    problem: "Most realtor websites are generic templates that look like everyone else's. Buyers see them and move on. Your website should be your hardest-working lead generator — not an afterthought.",
    icon: '🏠',
    color: '#6c5ce7',
    tiers: {
      basic: {
        name: 'Agent Lead Page',
        price: 179,
        priceId: process.env.STRIPE_PRICE_REALESTATE_BASIC || 'price_placeholder',
        features: [
          '1 professional agent page',
          'Lead capture form',
          'Featured listings section',
          'Testimonials & reviews',
          'Professional bio section',
          'Mobile optimized',
          '+ Choose a hosting plan below',
        ],
      },
      standard: {
        name: 'Realtor Website',
        price: 499,
        priceId: process.env.STRIPE_PRICE_REALESTATE_STANDARD || 'price_placeholder',
        features: [
          'Up to 6 pages',
          'Property search integration',
          'Buyer & seller resource guides',
          'Market stats section',
          'Email newsletter setup',
          'Professional bio + team pages',
          'Neighborhood highlights',
          '+ Choose a hosting plan below',
        ],
        popular: true,
      },
      premium: {
        name: 'IDX/MLS Integration Build',
        price: 1099,
        priceId: process.env.STRIPE_PRICE_REALESTATE_PREMIUM || 'price_placeholder',
        features: [
          'Full IDX/MLS integration',
          'Advanced property search & filters',
          'Lead scoring + CRM connection',
          'Automated market report pages',
          'Neighborhood & community pages',
          'Mortgage calculator tool',
          '30-day post-launch support',
          '+ Choose a hosting plan below',
        ],
      },
    },
    faq: [
      { q: 'Can you integrate with my MLS/IDX?', a: 'Yes, on the Premium plan. IDX integration requires a third-party IDX provider (e.g., iHomefinder, IDX Broker). We configure the integration — you handle the IDX subscription.' },
      { q: 'Do I need to write my own bio and content?', a: 'We provide a questionnaire that guides you through it. You supply the key details and we write professional copy for your site.' },
      { q: 'How do I update my featured listings?', a: 'We can set up easy self-editing for listings, or you can send us updates and we handle it — included in your hosting plan.' },
      { q: 'I have a brokerage — can you build for my whole team?', a: 'Absolutely. Contact us for a custom team/brokerage website quote.' },
    ],
  },
  'law-firms': {
    id: 'law-firms',
    name: 'Law Firms & Attorneys',
    slug: 'law-firms',
    headline: 'A law firm website that converts consultations — built, hosted, and maintained for you.',
    subheadline: 'Clients Google their attorney before they call. We build authoritative law firm websites that establish credibility and fill your consultation calendar.',
    problem: "Potential clients judge your firm's credibility by your website before they ever speak to you. A generic or outdated site loses you cases to competitors who invested in their online presence.",
    icon: '⚖️',
    color: '#0984e3',
    tiers: {
      basic: {
        name: 'Credibility Landing Page',
        price: 199,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_BASIC || 'price_placeholder',
        features: [
          '1 professional landing page',
          'Practice areas overview',
          'Consultation request form',
          'Attorney bio & credentials',
          'Trust signals & badges',
          'Mobile optimized',
          '+ Choose a hosting plan below',
        ],
      },
      standard: {
        name: 'Firm Website',
        price: 599,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_STANDARD || 'price_placeholder',
        features: [
          'Up to 8 pages',
          'Individual practice area pages',
          'Attorney profile pages',
          'Case results section',
          'Blog/article setup for SEO',
          'Client intake optimization',
          'Live chat integration',
          '+ Choose a hosting plan below',
        ],
        popular: true,
      },
      premium: {
        name: 'Multi-Practice + Intake Optimization',
        price: 1299,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_PREMIUM || 'price_placeholder',
        features: [
          'Multiple practice area microsites',
          'Advanced intake forms & routing',
          'Online scheduling integration',
          'Local SEO package',
          'Authority schema markup',
          'ADA compliance review',
          'Google Business optimization',
          '30-day post-launch support',
          '+ Choose a hosting plan below',
        ],
      },
    },
    faq: [
      { q: 'Is my content attorney-client privileged or confidential?', a: 'All content you provide during onboarding is handled confidentially and used solely to build your website.' },
      { q: 'Can the site include a client intake form?', a: 'Yes — intake forms are included in Standard and Premium. We can connect them to your case management system or email.' },
      { q: 'Do you handle bar compliance for advertising rules?', a: 'We recommend you review the final copy against your state bar\'s advertising guidelines. We\'ll incorporate any required disclaimers you specify.' },
      { q: 'How quickly can we launch?', a: 'Credibility pages in 5–7 days. Standard firm sites in 10–14 days. Premium builds 14–21 days after onboarding.' },
    ],
  },
} as const

export type NicheKey = keyof typeof NICHE_PRICES

export const HOSTING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    priceId: process.env.STRIPE_PRICE_HOSTING_STARTER || 'price_placeholder',
    features: [
      'Managed hosting',
      'SSL certificate',
      'Custom domain setup',
      'Global CDN (fast loading)',
      'Uptime monitoring',
      'Security updates',
      'Monthly backups',
      'Email support',
    ],
    recommended: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 49,
    priceId: process.env.STRIPE_PRICE_HOSTING_PROFESSIONAL || 'price_placeholder',
    features: [
      'Everything in Starter',
      'Up to 2 content updates/month',
      'Priority support (24hr response)',
      'Dedicated point of contact',
    ],
    recommended: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: 79,
    priceId: process.env.STRIPE_PRICE_HOSTING_BUSINESS || 'price_placeholder',
    features: [
      'Everything in Professional',
      'Up to 5 content updates/month',
      'Monthly performance report',
      'Basic SEO monitoring',
      'Quarterly strategy call',
    ],
    recommended: false,
  },
]
