export const NICHE_PRICES = {
  contractors: {
    id: 'contractors',
    name: 'Contractors & Trades',
    slug: 'contractors',
    headline: 'A contractor website that generates leads — built, hosted, and maintained for you.',
    subheadline: 'Stop losing jobs to competitors with better websites. We build professional contractor sites that convert visitors into booked work.',
    problem: "You're great at your trade — not at managing websites. Figuring out hosting, SSL, slow mobile pages, and why your contact form stopped working shouldn't be part of your job.",
    icon: '🔨',
    color: '#f39c12',
    tiers: {
      starter: {
        name: 'Starter',
        price: 499,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_STARTER || 'price_placeholder',
        features: [
          '5-page custom website',
          'Mobile-first responsive design',
          'Contact & quote request form',
          'Google Maps integration',
          'Basic local SEO setup',
          '30-day email support',
        ],
      },
      pro: {
        name: 'Pro',
        price: 1299,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_PRO || 'price_placeholder',
        features: [
          'Everything in Starter',
          'Up to 12 pages',
          'Custom design (2 revision rounds)',
          'Project gallery & before/after slider',
          'Google Reviews integration',
          'Advanced local SEO + schema',
          'Quote/booking form integration',
          '90-day support',
        ],
        popular: true,
      },
      elite: {
        name: 'Elite + AI',
        price: 1999,
        priceId: process.env.STRIPE_PRICE_CONTRACTOR_ELITE || 'price_placeholder',
        features: [
          'Everything in Pro',
          'Unlimited pages',
          'AI lead qualification chatbot',
          'Automated follow-up emails',
          'CRM integration',
          'Priority support',
          'Monthly performance report',
        ],
      },
    },
    faq: [
      { q: 'How long does it take to build my site?', a: 'Most contractor sites are live within 7–14 days after your onboarding call. Premium builds may take up to 21 days.' },
      { q: 'Do I need to provide content and photos?', a: "We'll guide you through a simple onboarding questionnaire. You provide your logo, photos of your work, and key business details — we handle the rest, including writing your copy." },
      { q: 'What if I already have a domain?', a: "No problem. We'll configure your existing domain to point to your new site. If you need a domain, we can register one for you." },
      { q: 'Can I make changes to my site?', a: 'Minor content updates (text, photos, hours) are included in your hosting plan. Major changes like new pages are available at a discounted hourly rate.' },
    ],
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-Commerce Stores',
    slug: 'ecommerce',
    headline: 'A Shopify store that sells — built, launched, and managed for you.',
    subheadline: 'Your competitors are converting visitors. We build Shopify stores optimized for sales, then manage them so you can focus on your products.',
    problem: "Setting up Shopify sounds simple until you're 4 hours deep trying to configure shipping zones, payment gateways, and theme settings. Then your sales are live but the store looks generic and converts at 1%.",
    icon: '🛍️',
    color: '#00cec9',
    tiers: {
      starter: {
        name: 'Starter',
        price: 999,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_STARTER || 'price_placeholder',
        features: [
          'Up to 50 products',
          'Shopify or WooCommerce',
          'Mobile-optimized checkout',
          'Payment gateway setup',
          'Basic product SEO',
          '30-day email support',
        ],
      },
      pro: {
        name: 'Pro',
        price: 1999,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_PRO || 'price_placeholder',
        features: [
          'Everything in Starter',
          'Unlimited products',
          'Custom design (2 revision rounds)',
          'Abandoned cart automation',
          'Email marketing integration',
          'Advanced product SEO',
          '90-day support',
        ],
        popular: true,
      },
      elite: {
        name: 'Elite + AI',
        price: 3999,
        priceId: process.env.STRIPE_PRICE_ECOMMERCE_ELITE || 'price_placeholder',
        features: [
          'Everything in Pro',
          'AI product recommendations',
          'Subscription billing system',
          'Multi-channel sync (Amazon, Meta)',
          'Custom analytics dashboard',
          'Priority support',
          'Monthly revenue report',
        ],
      },
    },
    faq: [
      { q: 'Do I need an existing Shopify account?', a: 'No. We set everything up from scratch. You will need a Shopify subscription (starting at $39/mo directly with Shopify) — this is separate from our build and hosting fees.' },
      { q: 'How long until my store is live?', a: 'Starter builds typically 5–10 days. Standard 10–14 days. Premium 14–21 days after onboarding.' },
      { q: 'What\'s included in managed Shopify maintenance?', a: 'We handle theme updates, app compatibility, minor content changes, and troubleshooting. Your store stays current and working without you touching the backend.' },
      { q: 'Can you migrate my existing store?', a: 'Yes — product migration from existing stores is available. Contact us for a custom quote if you have more than 50 products.' },
    ],
  },
  'real-estate': {
    id: 'real-estate',
    name: 'Realtors & Real Estate',
    slug: 'real-estate',
    headline: 'A real estate website that captures leads — built, hosted, and maintained for you.',
    subheadline: 'Buyers and sellers Google their agent before they call. We build real estate sites that establish credibility and capture serious leads.',
    problem: "Most realtor websites are generic templates that look like everyone else's. Buyers see them and move on. Your website should be your hardest-working lead generator — not an afterthought.",
    icon: '🏠',
    color: '#6c5ce7',
    tiers: {
      starter: {
        name: 'Starter',
        price: 699,
        priceId: process.env.STRIPE_PRICE_REALESTATE_STARTER || 'price_placeholder',
        features: [
          '5-page agent website',
          'Listing showcase gallery',
          'Lead capture form',
          'Neighbourhood area pages',
          'Basic SEO setup',
          '30-day email support',
        ],
      },
      pro: {
        name: 'Pro',
        price: 1399,
        priceId: process.env.STRIPE_PRICE_REALESTATE_PRO || 'price_placeholder',
        features: [
          'Everything in Starter',
          'Up to 12 pages',
          'IDX/MLS integration ready',
          'Seller & buyer landing pages',
          'Advanced lead capture forms',
          'Market area content pages',
          'CRM connection',
          '90-day support',
        ],
        popular: true,
      },
      elite: {
        name: 'Elite + AI',
        price: 2799,
        priceId: process.env.STRIPE_PRICE_REALESTATE_ELITE || 'price_placeholder',
        features: [
          'Everything in Pro',
          'Unlimited pages',
          'AI property matching chatbot',
          'Automated buyer/seller drip',
          'SMS lead alerts',
          'Full CRM integration',
          'Priority support',
          'Monthly analytics report',
        ],
      },
    },
    faq: [
      { q: 'Can you integrate with my MLS/IDX?', a: 'Yes, on the Premium plan. IDX integration requires a third-party IDX provider (e.g., iHomefinder, IDX Broker). We configure the integration — you handle the IDX subscription.' },
      { q: 'Do I need to write my own bio and content?', a: 'We provide a questionnaire that guides you through it. You supply the key details and we write professional copy for your site.' },
      { q: 'How do I update my featured listings?', a: 'We can set up easy self-editing for listings, or you can send us updates and we handle it — included in your hosting plan.' },
      { q: 'I have a brokerage — can you build for my whole team?', a: 'Absolutely. Contact us for a custom team/brokerage website quote.' },
    ],
  },
  'law-firms': {
    id: 'law-firms',
    name: 'Law Firms & Attorneys',
    slug: 'law-firms',
    headline: 'A law firm website that converts consultations — built, hosted, and maintained for you.',
    subheadline: 'Clients Google their attorney before they call. We build authoritative law firm websites that establish credibility and fill your consultation calendar.',
    problem: "Potential clients judge your firm's credibility by your website before they ever speak to you. A generic or outdated site loses you cases to competitors who invested in their online presence.",
    icon: '⚖️',
    color: '#0984e3',
    tiers: {
      starter: {
        name: 'Starter',
        price: 699,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_STARTER || 'price_placeholder',
        features: [
          '5-page firm website',
          'Practice areas overview',
          'Consultation request form',
          'Attorney bio & credentials',
          'Trust signals & badges',
          'Mobile optimized',
          '30-day email support',
        ],
      },
      pro: {
        name: 'Pro',
        price: 1699,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_PRO || 'price_placeholder',
        features: [
          'Everything in Starter',
          'Up to 12 pages',
          'Individual practice area pages',
          'Attorney profile pages',
          'Case results section',
          'Blog/article setup for SEO',
          'Client intake optimization',
          'Live chat integration',
          '90-day support',
        ],
        popular: true,
      },
      elite: {
        name: 'Elite + AI',
        price: 3499,
        priceId: process.env.STRIPE_PRICE_LAWFIRM_ELITE || 'price_placeholder',
        features: [
          'Everything in Pro',
          'Unlimited pages',
          'AI intake qualification chatbot',
          'Advanced intake forms & routing',
          'Online scheduling integration',
          'Full CRM integration',
          'Priority support',
          'Monthly analytics report',
        ],
      },
    },
    faq: [
      { q: 'Is my content attorney-client privileged or confidential?', a: 'All content you provide during onboarding is handled confidentially and used solely to build your website.' },
      { q: 'Can the site include a client intake form?', a: 'Yes — intake forms are included in Standard and Premium. We can connect them to your case management system or email.' },
      { q: 'Do you handle bar compliance for advertising rules?', a: 'We recommend you review the final copy against your state bar\'s advertising guidelines. We\'ll incorporate any required disclaimers you specify.' },
      { q: 'How quickly can we launch?', a: 'Credibility pages in 5–7 days. Standard firm sites in 10–14 days. Premium builds 14–21 days after onboarding.' },
    ],
  },
  'web-design': {
    id: 'web-design',
    name: 'Custom Web Design',
    slug: 'web-design',
    headline: 'A premium custom website built for your brand.',
    subheadline: 'Full custom design, development, and launch — handled entirely by us.',
    problem: "Your website is your first impression. We build custom sites that convert.",
    icon: '🎨',
    color: '#6c5ce7',
    tiers: {
      basic: {
        name: 'Starter Package',
        price: 2249,
        priceId: process.env.STRIPE_PRICE_WEB_STARTER || 'price_placeholder',
        features: [
          '5-page custom website',
          'Responsive design',
          'Basic SEO setup',
          'Contact form',
          '30 days support',
          '+ Monthly hosting below',
        ],
      },
      standard: {
        name: 'Professional Package',
        price: 5999,
        priceId: process.env.STRIPE_PRICE_WEB_PRO || 'price_placeholder',
        features: [
          'Up to 20 pages',
          'E-commerce ready',
          'Advanced SEO',
          'AI chatbot integration',
          '3 months support',
          'Analytics setup',
          '+ Monthly hosting below',
        ],
        popular: true,
      },
    },
    faq: [],
  },
  'solar-ai': {
    id: 'solar-ai',
    name: 'Solar AI Agent',
    slug: 'solar-ai',
    headline: 'AI-powered solar permit automation — proposals to permits in minutes.',
    subheadline: 'Drop your proposal and customer bill in, get contracts, drawings, SLDs, and permit applications out. Fully automated.',
    problem: "You're spending hours on paperwork that a machine can do in minutes. Solar AI handles contracts, DXF drawings, single-line diagrams, and permit forms — so you can install more panels.",
    icon: '☀️',
    color: '#f59e0b',
    tiers: {
      monthly: {
        name: 'Monthly Plan',
        price: 500,
        priceId: process.env.STRIPE_PRICE_SOLAR_AI_MONTHLY || 'price_placeholder',
        features: [
          'Full Solar AI automation suite',
          'Contract auto-generation',
          'DXF layout drawings',
          'Single-line diagram generation',
          'Permit-ready document generation',
          'Cancel anytime — no lock-in',
        ],
      },
      annual: {
        name: 'Annual Plan',
        price: 3000,
        priceId: process.env.STRIPE_PRICE_SOLAR_AI_ANNUAL || 'price_placeholder',
        features: [
          'Everything in Monthly',
          '6 months free vs. monthly',
          'Priority onboarding & support',
          'Dedicated account manager',
          'Cancel anytime — prorated refund',
        ],
        popular: true,
      },
    },
    faq: [
      { q: 'What do I need to get started?', a: 'Just your proposal template and a sample customer bill. Our onboarding team will configure your Solar AI agent within 48 hours.' },
      { q: 'Which permit authorities are supported?', a: 'We support all major Canadian municipalities and wire service providers. If your area isn\'t covered yet, we\'ll add it during onboarding at no extra cost.' },
      { q: 'Can I cancel anytime?', a: 'Yes — monthly plans cancel anytime with no penalty. Annual plans can be cancelled for a prorated refund of unused months.' },
      { q: 'Do I need technical knowledge to use this?', a: 'Not at all. You drag and drop files, and the AI handles everything. If you can attach a PDF to an email, you can use Solar AI.' },
    ],
  },
} as const

export type NicheKey = keyof typeof NICHE_PRICES

export const HOSTING_PLANS = [
  {
    id: 'none',
    name: 'No Hosting',
    price: 0,
    priceId: 'price_none',
    features: [
      'SaaS subscription — no hosting required',
    ],
    recommended: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    priceId: process.env.STRIPE_PRICE_HOSTING_STARTER || 'price_placeholder',
    features: [
      'Managed hosting',
      'SSL certificate',
      'Custom domain setup',
      'Global CDN (fast loading)',
      'Uptime monitoring',
      'Security updates',
      'Monthly backups',
      'Email support',
    ],
    recommended: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 49,
    priceId: process.env.STRIPE_PRICE_HOSTING_PROFESSIONAL || 'price_placeholder',
    features: [
      'Everything in Starter',
      'Up to 2 content updates/month',
      'Priority support (24hr response)',
      'Dedicated point of contact',
    ],
    recommended: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: 79,
    priceId: process.env.STRIPE_PRICE_HOSTING_BUSINESS || 'price_placeholder',
    features: [
      'Everything in Professional',
      'Up to 5 content updates/month',
      'Monthly performance report',
      'Basic SEO monitoring',
      'Quarterly strategy call',
    ],
    recommended: false,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 129,
    priceId: process.env.STRIPE_PRICE_HOSTING_ENTERPRISE || 'price_placeholder',
    features: [
      'Everything in Business',
      'Unlimited content updates',
      'Dedicated account manager',
      'Priority 4hr response SLA',
      'Monthly strategy call',
      'Advanced analytics & reporting',
      'Uptime SLA guarantee',
    ],
    recommended: false,
  },
]
